### ISSUE TITLE
TEST BUILD 11

### ISSUE THREAD

**Issue by spadino** [WhiteMagic/JoystickGremlin#100]
Everything works very smooth. So far, I just noticed minor issues:

- Input Viewer do not draw the movement of the joystick, however the values is correctly saw by the games.
- The window could remember its states (maximized, minimized, etc...), if possible.
- How about an option to enable a profile as soon as the program load?

Thanks for your great work!

**Comment by WhiteMagic** [comment]
I've so far only implemented one of the axis value visualization things, the time graph one. The other one which will display it similar to how Window's joy.cpl does I haven't gotten around to yet. If both don't show anything then that's odd.

Gremlin remembers position and size which I guess doesn't work for maximize and obviously not for minimize. There is an option to have it start minimized but making it remember those states probably isn't too hard.

The loading of a profile upon launch is actually already possible, though it requires passing command line arguments to Gremlin on startup. https://whitemagic.github.io/JoystickGremlin/interface/ all the way at the bottom has info on that. It was implemented as a way for people to control some startup actions before the "Launch with Windows" option became a thing. The option is obviously to use the profile auto loading which would load and activate a profile when you switch to a specified application. Though I may see if adding the two command line options to the options menu would work as well.

**Comment by WhiteMagic** [comment]
#109 Option replicating `--enable` in the UI.
