### ISSUE TITLE
Custom Module

### ISSUE THREAD

**Issue by spadino** [WhiteMagic/JoystickGremlin#101]
I'm trying to understand how to work with custom modules. I have many snippets which I made in FreePIE which I want to port to JG and share.

Now, I want to try to put to work a very simple sketch:

```
import gremlin
from vjoy.vjoy import AxisName

def set_headlook_X(vjoy, value):
    vjoy[2].axis(AxisName.X).value = value

def set_headlook_Y(vjoy, value):
    vjoy[2].axis(AxisName.Y).value = value

@gremlin.input_devices.keyboard("8", "Global")
def look_UP(event, vjoy):
    if event.is_pressed:
        set_headlook_Y(vjoy, -0.1)
       
@gremlin.input_devices.keyboard("7", "Global")
def look_LEFT(event, vjoy):
    if event.is_pressed:
        set_headlook_X(vjoy, -0.1)

@gremlin.input_devices.keyboard("9", "Global")
def look_RIGHT(event, vjoy):
    if event.is_pressed:
        set_headlook_X(vjoy, 0.1)

@gremlin.input_devices.keyboard("0", "Global")
def look_DOWN(event, vjoy):
    if event.is_pressed:
        set_headlook_Y(vjoy, 0.1)
```

I wrote that and saved it in a file called headlook.py. I succesfully loaded it in JG User Module panel 
![image](https://user-images.githubusercontent.com/4296635/39316598-e80baf98-494f-11e8-9b8c-58c875ed7356.png)
but I didn't understood what I have to do now. How can I have it recognized and work? It does not seem to have any effect...

**Comment by spadino** [comment]
Thanks! I’ll give the source a good look, to figure out better how things are implemented. Loving this tool! ❤️

**Comment by WhiteMagic** [comment]
Closing for now, just reopen etc. when there are more questions.
