### ISSUE TITLE
Unexpectet behaviour in condition with remap like actions

### ISSUE THREAD

**Issue by Francky63** [WhiteMagic/JoystickGremlin#103]
I don't know if my "logic" is wrong or if is an error but ... 
i would like to setup that Button X on my stick it enable vJoy button Y But only if Button Z on the stick is pressed.

this is a normal way to setup shifted function in falcon with TH Cougar..

What it happen is that if I release Button Z before Button X, vJoy Button Y it remain ON. I have to switch ON again X and Z to switch off Y...

Z is a conditional button if condition is not meet action could not be performed.

I expected that if i set RELEASE Button Z in condition Y it remain ON but in this case nothing it happen

Now i worked around with a TEMPO action because one pulse is enough  

Regards
Franco

**Comment by WhiteMagic** [comment]
Technically Gremlin is performing as it was programmed to but it's not very intuitive for this particular case I'd say. Gremlin checks whether or not a condition associated with an action is true both on the "press" and "release" of the associated physical input. In most cases this works fine as they only trigger once (macro, mode switch, etc.) The usual one that complicates everything are remaps as they trigger twice both on press and release. I'll have to see if I can reuse the code that makes this behave properly when switching modes (they used to have the same issue with buttons being stuck down).

One possible workaround, although painful to use, is to have two actions with macros. One for the press and one for the release part of it. The press one would only activate when the condition is satisfied while the release one would always release the button.

**Comment by WhiteMagic** [comment]
The auto release function was only triggering if a mode had changed. In the case of shift conditions this would not trigger. This has been changed such that auto-release actions are always run and in that manner even letting go of a shift button while the shifted action is active will ensure that the release action of the shifted input is run.

f84945a0144639b992c93c6da866a1a2b1ddf3d6
