### ISSUE TITLE
Add a visual indicator to the taskbar icon to show current state (enabled / disabled)

### ISSUE THREAD

**Issue by Francky63** [WhiteMagic/JoystickGremlin#105]
Enable / Disable function with right click in task bar is very useful but there is no feed back of the current status of Joystick Gremlin you have to show it to know if now is enabled or disabled

**Comment by WhiteMagic** [comment]
I guess that should be easily solved by changing the color or adding some tiny blip to the icon shown in the taskbar.

**Comment by WhiteMagic** [comment]
Implemented with cfd826d2597b3d44ad525e93f72821198094d4a4 which adds a small red circle to the system tray icon when Gremlin is active.
