### ISSUE TITLE
run minimized as Comand Line option

### ISSUE THREAD

**Issue by Francky63** [WhiteMagic/JoystickGremlin#106]
The option parameter is good but if you need to work on config you need to run it as window...
in the same time that you --enable a --profile from comand line could be useful to --minimize it 
in this way you can have a operative link that run JG ready to use and a link for develop new option

Sorry but i'm looking heavily inside JG is an amazing utility i hope this suggestion/issue could be useful to your application

**Comment by WhiteMagic** [comment]
I can see about adding the command line option though for now the "Start Joystick Gremlin Minimized" bit in the option should achieve the same thing, assuming it doesn't somehow clash with the command line bits and gets not used (as I haven't tested this).

Don't worry about providing suggestions they help showing what use cases people have. They may take a while to get added or get added differently based on how I can make them generic enough to be of general use and make them work within the restrictions of how Gremlin is designed.

**Comment by WhiteMagic** [comment]
Implemented in e098e610321d9f33d1c25354d1c56ee97e4a0382. This adds the `--start-minimized` command line option which causes Gremlin to launch minimized.
