### ISSUE TITLE
How to get a a profile to auto start on open

### ISSUE THREAD

**Issue by Meekstaaa** [WhiteMagic/JoystickGremlin#108]
Hi,

This program is amazing. So much better than what I was using before.

I've managed to get everything setup but I'm having trouble getting my profile to auto start when it starts with windows.

Could you please advise how to do the command line parameter. I'm a bit of a noob at all this!

**Comment by WhiteMagic** [comment]
There is actually no direct way to do this via the options UI ... really should add that. But you can either add the `--enable` flag to the Gremlin when launching it via a shortcut. Alternatively with R11 you could also abuse the automatic loading of profiles by using `.*` as the regular expression to match any program running and thus activating the specified profile all the time.

**Comment by Meekstaaa** [comment]
Managed to get it working by making it load my profile when it sees one of the default programs that auto launch with windows :)

Any idea on this new Vjoy not working with the new version of windows?

**Comment by Meekstaaa** [comment]
The above doesn't work as it only is activated when that program has focus.

Managed to get the enable flag working on the startup shortcut.

**Comment by WhiteMagic** [comment]
The flag is the clean solution until the next release where I added an option for that in the UI. The autoload feature should work if you make it match everything, i.e. using a regular expression of `.*`. Though that may still enable and disable the profile every time the foreground process switches.

**Comment by WhiteMagic** [comment]
Implemented in b286444b31c58c5981c5f2862457708af713d0d3
