### ISSUE TITLE
vJoy issue with new windows 10 build

### ISSUE THREAD

**Issue by Meekstaaa** [WhiteMagic/JoystickGremlin#110]
Hi,

Not sure if you know but with the latest version of windows (1803) but vJoy has stopped working for some reason. People are having a few issues getting it to even work.

My vJoy sets up ok but now is not responding to JoystickGremlin inputs from other controllers

**Comment by WhiteMagic** [comment]
I haven't encountered the issue yet, but then again I haven't checked if my windows decided to update yet. There is an issue on the vJoy github where Shaul seems to have found some steps that seem to possibly make things work again but it's not necessarily fixing it for good by the sounds of it.

https://github.com/shauleiz/vJoy/issues/20
The following is his post which seems to partially fix things but depending on what you do afterwards it may break again apparently.
> I have been going through the code to find where vJoy accesses the registry.
Here is what I found:
Configuration is under: registry key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\vjoy
FFB stuff is under: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Setup\PnpResources\Registry\HKLM\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM\VID_1234&PID_BEAD
>
> However, the system itself adds many other entries. Here's what I found:
HKEY_CURRENT_USER\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\DirectInput\VID_1234&PID_BEAD
>
> HKEY_USERS\S-1-5-21-2818827853-3098010898-2971523946-1001\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\DirectInput\VID_1234&PID_BEAD
>
> HKEY_CURRENT_USER\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM\VID_1234&PID_BEAD
>
> HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Setup\PnpResources\Registry\HKLM\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM\VID_1234&PID_BEAD
>
> HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\MediaProperties\PrivateProperties\Joystick\OEM\VID_1234&PID_BEAD
>
> HKEY_USERS\S-1-5-21-2818827853-3098010898-2971523946-1001\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM\VID_1234&PID_BEAD
>
> Please note that where my machine has S-1-5-21-2818827853-3098010898-2971523946-1001 your machine will have something else. the HKEY_USERS\S* is an arbitrary string.
>
> I suggest that you try to uninstall vJoy, remove all the above entries and try to reinstall afresh. This might just solve the problem (or not).

**Comment by Meekstaaa** [comment]
Ah. I found out why my vJoy stopped working.

I stupidely set it to auto start when it see's joystick gremlin. It only activates when that is the widow in focus. So when I went into it to edit everything was fine but when I went out it stopped working!

**Comment by WhiteMagic** [comment]
Shaul fixed the bug which was apparently caused by defining a vJoy device with 0 buttons. The tools now no longer allow this. The fix seems to be only the config tools and not the driver itself.

The latest version that prevents this issue can be grabbed here https://github.com/shauleiz/vJoy/releases/download/v2.1.8.39/vJoySetup.exe
