### ISSUE TITLE
Merge Axis 

### ISSUE THREAD

**Issue by Francky63** [WhiteMagic/JoystickGremlin#114]
A friend of my asked me if it is possible to merge the axis, he has a car pedals but he need to use it has a plane rudder.

**Comment by WhiteMagic** [comment]
Yep you can merge arbitrary axis via the UI. It's somewhat hidden as I couldn't think of a good way to add it to the device axis directly.

To merge two axis go to Actions -> Merge Axis, then click on the New Axis button. There you can then pick the two axis that form the lower and upper half of the new axis, i.e. from -1 to 0 and from 0 to 1. Then assign that to the desired vJoy axis and mode (if there are multiple).

If you need a response curve on the merged axis you can achieve that by adding a response curve to the vJoy axis used as the output for the merged axis in the corresponding vJoy tab. This is actually the main reason the vJoy tabs even exist, to allow adding response curves to them when doing some more advanced stuff like merge and split axis.
