### ISSUE TITLE
Vjoy axis preset values are not loaded in Settings tab

### ISSUE THREAD

**Issue by ssiril** [WhiteMagic/JoystickGremlin#116]
Hi, 
Axis preset in Settings tabs can be changed, saved in xml, are correctly applied when running the script but are not loaded correcly when opening a xml or (re)starting Joystick Gremlin since Release 11.

Regards,

C.G.

**Comment by WhiteMagic** [comment]
Thanks for catching that one, was an easy fix once I looked for it ... one type and everything breaks :-(. Fixed with aec91e63d933da42d4f5432952d48e3a8c2b97c5.

**Comment by ssiril** [comment]
Yup I was looking around in the code bug not skilled enough to self fix and build locally :)

Thanks however :)

ps: you are doing and incredibly great job with gremlin ! you absolutely saved my life with my (too) many joystick setup !
