### ISSUE TITLE
Issue with Macro/Button Remap

### ISSUE THREAD

**Issue by Rabidscoobie** [WhiteMagic/JoystickGremlin#124]
Im new to JG and I have almost everything working perfect except for 2 things and I cant figure out or not sure if its a limitation with the program.

1. JG isnt detecting multiple buttons presses simultaneously. It will only allow one or the other. I'm really hoping this isnt a limitation. 
So lets say I have a weapon group 1 and weapon group 2 on 2 different buttons, if I hold both down JG only sees the 1st button pushed. Also if I push any other button while WPN Group 1 is pressed it either doesnt register the 2nd button or stops the 1st.

2. I assigned lets say my "JS trigger" button as a macro for the remap of the "left mouse button". Now I have it working and to fire as long as i hold the trigger down but it fires slower than what the actual mouse button does. 

Am I doing something wrong in the macro or is it just the software?
If I am doing something wrong then how do I correct these issues?

Thanks, seems like a great program if I can get the above working as intended.

**Comment by WhiteMagic** [comment]
Closing this, given we've, at least for now, resolved these issues on spectrum.
