### ISSUE TITLE
response curve

### ISSUE THREAD

**Issue by Francky63** [WhiteMagic/JoystickGremlin#125]
in the example movie it look like you remap directly the joystick axis and not an axis remap is it true? (because from my test it doesn't work) or have you to remap axis?

thanks

**Comment by WhiteMagic** [comment]
If you are referring to the "Custom axis response curve" one then yeah that won't result in actually outputting anything to a vJoy device, you'd need to add the remap action to that as well. I probably should change that.

The response curve only results in the received physical value to be modified locally for the set of actions. So in order for that value to appear on a vJoy device it then has to be remapped to one.

While there are instances where you might want a changed response curve without a remap those use cases are rather obscure compared to the one where it is combined with a remap.
