### ISSUE TITLE
Initial vJoy axes values won't load

### ISSUE THREAD

**Issue by rishp** [WhiteMagic/JoystickGremlin#127]
I've modified the initial vJoy axes values in the settings tab and saved the config. When I restart the program and load the config the values reset to zero. I can see the values are being saved in the config file but the program won't load them.

**Comment by WhiteMagic** [comment]
I think I've had other people point this bug out to me as well. Most likely easy to fix but obviously quite annoying until it is. I'm probably going to finish the one big feature for the next version and release that together with a bunch of fixes for easy but annoying bugs.

**Comment by WhiteMagic** [comment]
Inadvertently (?) fixed in the current features branch.
