### ISSUE TITLE
Question - scan code table

### ISSUE THREAD

**Issue by Eetsjone** [WhiteMagic/JoystickGremlin#128]
Hello,

Can you give the table used for the keyboard scan codes?
On my keyboard I do not have a right-win-key or right-menu-key like in the standard US keyboard.
After testing it appears that decimal values > "93" (scan codes in xml file) are not recognized and therefore cannot be entered into the xml file with Notepad++. I was able to enter value "92" for right-win-key but not "165" for right-menu-key. 

When I tried value "165" JG showed hex value 0x0 (=nothing).

Regards,

Huub.

**Comment by Eetsjone** [comment]
Thank you very much for your reply. I understand now what I can do to get the keys working.

Thank you also very much for your program as it is a great tool to get my console working.

**Comment by WhiteMagic** [comment]
No problems, if there are other questions / problems feel free to ask.
