### ISSUE TITLE
Crashes if a USB device (memory) is unplugged while JoyGr is active

### ISSUE THREAD

**Issue by Artyrm** [WhiteMagic/JoystickGremlin#129]
I get numerus errors like this:

![image](https://user-images.githubusercontent.com/21180686/44932533-7a05ac00-ad6e-11e8-8f9d-0337f5b4e59c.png)

And nothing in logs. I can confirm this on numerous machines with win7/10 and various devices.

**Comment by WhiteMagic** [comment]
Is there anything specific about the memory stick or does this happen with arbitrary ones? I quickly tried and couldn't get Gremlin to spit errors like the ones you get at me.

**Comment by Artyrm** [comment]
No, I could reproduce it with USB HDD as well. But I have to wait until Windows detects it like mass storage and shows its content, so with stick it happens fast and with USB dsik slow (if I plug it out before that, no errors happen). And ofc it just crashes (without those errors) if I plug in or plug out another gamepad.

Here are some more details. It happens with PS4 gamepad. I tried also PS3 gamepad (need some tricks to work under Win7) and Logitech F310. With those two JoyGr doesn't spit errors right away, but rather crashes if I try to de-activate it _after_ USB device was plugged out.


And the most important observation: I believe it is more profile-specific. Because if I try this with new empty profile, then no errors whatsoever. So here is my profile.
[PS4.zip](https://github.com/WhiteMagic/JoystickGremlin/files/2343109/PS4.zip)

The main difference between PS4 gamepad and those two is what it has sensor slider and two more buttons (which are combined with triggers 'axis'). BTW here is my vJoy config.
![image](https://user-images.githubusercontent.com/21180686/44954045-d0c1d180-aea5-11e8-8aa7-62f13af7cca5.png)

**Comment by WhiteMagic** [comment]
Thanks for the additional detail I'll see if I can figure out what's going on with that.

**Comment by Artyrm** [comment]
Is there something I could help you with this? Some additional tests, maybe?

**Comment by WhiteMagic** [comment]
Not at this point, I mainly just don't have enough time lately. I'm still working on the one feature I want to add for the new release before I go and hunt and fix a bunch of bugs to go with that.

**Comment by WhiteMagic** [comment]
Fixed with 5fe03f8513afdd69cc47f53d6ac37672e1d86ddb
