### ISSUE TITLE
Double tap container

### ISSUE THREAD

**Issue by WhiteMagic** [WhiteMagic/JoystickGremlin#144]
Add a new container type which requires a double tap to activate the contents.

**Comment by muchimi** [comment]
While the tempo feature adds the ability to do a short press and a long press, another, although probably less common input change mode, is to distinguish between an action on single tap vs double tap. 

This would be another option below the tempo feature.

Use-cases:  (1) some avionics control systems require the pilot to pickle a button twice to either cycle or lock a target, (2) to select a waypoint on a map with a moving cursor.   (3) communication ack usually is a click-click (or double tap on the PTT key).

This can be done in JG currently with a custom module - it would be nice to have that built-in as another option below the tempo() function.

**Comment by WhiteMagic** [comment]
Thanks to @jmriego for implementing this feature.
