### ISSUE TITLE
"Please wait while windows configures Joystick Gremlin" each time I run the application

### ISSUE THREAD

**Issue by Skarafaz** [WhiteMagic/JoystickGremlin#157]
Hi! Each time I run Joystick Gremlin (installed from msi) Windows configures it as it was just installed, is that normal? It keeps creating the desktop icon and it is quite annoying. Thanks, the software is awesome.

**Comment by WhiteMagic** [comment]
No that's not really what should happen. This is probably something odd with how the installer behaved on your system. I think this happened to someone else at some point as well but I don't know if / how that got fixed, as I never was able to coax my windows install into doing that.

I would assume that the zip version (which is the same content without an installer) wouldn't cause this to happen.

**Comment by Skarafaz** [comment]
Ok thanks! I'll use the zip
