### ISSUE TITLE
`Hat Buttons` not working on second stick

### ISSUE THREAD

**Issue by JoeSchr** [WhiteMagic/JoystickGremlin#158]
Hi there,

I was just stumbling over a little bug. I'm currently configuring a dual stick scenario. 
On my first stick I'm using the `Hat Button` helper with North, East, South, West containers.

When I tried to do this on my second stick, I doesn't work. I'm using `Map to Keyboard` on every action and it doesn't register any keypress after triggering via the hat. On the other stick it works. It also works when I use 4 single `Map to Keyboard` actions and then set it via the `Virtual Button` side config. 

It's not a huge bug and but I thought I at least post my workaround for other people. 
Also I'm just interested if I'm doing anything completely wrong, but wouldn't know what since it works on my first stick. Maybe you see something obviously wrong? Thank you.

**Comment by WhiteMagic** [comment]
While every Hat Button container should be independent of every other container and thus there should be no such weird interaction it's not impossible that there is something funny I overlooked when implementing this. I'll have to look into that.

**Comment by WhiteMagic** [comment]
It really should just behave as one would expect, e.g. a map to keyboard with nothing associated should do nothing while a tempo container with only  the long press action configured should simply just only do the long press.

It shouldn't be too much work updating all the containers to behave in a more expected manner anyways.
