### ISSUE TITLE
Implement a `Map to mouse BUTTON` action

### ISSUE THREAD

**Issue by JoeSchr** [WhiteMagic/JoystickGremlin#159]
Hi, is it possible to add a `map to mouse BUTTON` action. I'm now using a workaround via a macro which presses and releases mouse button, but it's a little weird with timings. I had to configure it to `hold` `0.00` seconds to work almost right. Took me quite a while to find that out, so a straightforward `map to mouse button` would be very nice. :D

**Comment by WhiteMagic** [comment]
Yeah probably can't hurt to add that function, it would most likely include all 5 buttons and the mouse wheel.

To get around timing issues you might be able to use two macros, one sending the "down" even and the second on the "up" event. Then adding container > action conditions to each of them to trigger on the physical "down" and "up" events. This is what the remap and map to keyboard actions do behind the scenes with some additional bookkeeping.

**Comment by JoeSchr** [comment]
Still thanks for all the work you are doing and don't let yourself get down by an evergrowing todo list. It's definitive an awesome software already! :D

**Comment by WhiteMagic** [comment]
No worries, the list is actually not growing all that much, it's more about prioritizing which thing to add first.

**Comment by WhiteMagic** [comment]
Basic mouse button support added to the `Map to Mouse` action with c01dcb4d0d51ceb2a626c964ad514b33f86cf2ca through cb2e328e1dd6755f4ef6ea5f283a816ba4d28471
