### ISSUE TITLE
Crash: float comma input boxes on systems with , instead of . as a comma

### ISSUE THREAD

**Issue by JoeSchr** [WhiteMagic/JoystickGremlin#160]
Hi,

I'm using a windows system were regeion -> customize format -> decimal symbol is set to `,` instead of english `.`. 
This makes JG crash sometimes when using the input boxes for float comma. Eg. delay time in pause macro. I think it maybe because there is `0.00` hardcoded as default value for these input boxes.

**Comment by WhiteMagic** [comment]
Thanks for the report, I'll have to see what causes this as the UI element for this is mainly stock Qt which should handle this, though some of the changes made to it probably don't cope with a different decimal point sign.

**Comment by WhiteMagic** [comment]
While I didn't manage to crash Gremlin when inputting "wrong" symbols when entering numbers such as the pause duration I did rework the logic such that it actually knows to use the appropriate decimal separator (see commit c7e6c3554a31112d26e7f02b75825bc33b0f2aa3).

There may be an other issue causing the crash, so if you still crash when the new version comes out reopen this bug or create a new one.

**Comment by JoeSchr** [comment]
will do, thanks! when is the new version coming out, so I can note to test it?

**Comment by WhiteMagic** [comment]
I'm done with my todo list for the new version and now I'll have to test as much as I can so catch all the things I've invariably broken by adding and "fixing" things. With any luck I'll get this done by the end of the week and if not it's going to be next week.

**Comment by JoeSchr** [comment]
That's amazing timing!

I was planning to do some MIDI to mouse mapping in the holidays, so I'm also looking forward to test the 
new mouse mapping feature! :D
