### ISSUE TITLE
Crash on startup with Wooting ONE Keyboard attached

### ISSUE THREAD

**Issue by loban4** [WhiteMagic/JoystickGremlin#166]
When I try to start JG it will silently crash.

I have a [Wooting One Keyboard](https://wooting.io/) which appears to be the cause of these Issues. When I unplug it i can start JG 11 normally. The keyboard is special because it features an analog mode in wich it acts as a game controller.

Afterwards I tried it with the 11.1 Version found here: #151 
With this Version it throws two errors related to "gremlin/ui/device_tab.py" (attached below) but eventually starts.

When I go into the input viewer and select/deselect the "Axes - Temporal" of one of the Wooting Ones (it only happens with one of them) I get another error message (attached below).

This is the system.log with multiple different attempts (with/without HOTAS/Wooting) and with [Wooting XInput activated and deactivated](https://wooting.helpscoutdocs.com/search?query=xinput).

[system.log](https://github.com/WhiteMagic/JoystickGremlin/files/2651142/system.log)

Error on startup:
![image](https://user-images.githubusercontent.com/16103422/49552784-4d28de00-f8f5-11e8-8fa1-c1b74b6ff9d4.png)

Error when selecting the axis:
![image](https://user-images.githubusercontent.com/16103422/49552717-1226aa80-f8f5-11e8-84c0-02e13d7dbae3.png)

**Comment by WhiteMagic** [comment]
The error in the first screenshot I may have fixed recently in the current dev version as some other device / device usage caused an error in the same spot.

The second one I suspect stems from the fact that the input viewer was written thinking only about DirectInput devices which can only have 8 axes. I'm not sure if the wooting is exposing every key as an individual axis or if there are issues with labelling things. The error looks like it's related to either selecting a color to show the graphs as, but I'll have to look at the code for that.

**Comment by WhiteMagic** [comment]
Closing for now, if this persists in the new version feel free to reopen this.
