### ISSUE TITLE
JG Crashes when trying to load saved profiles

### ISSUE THREAD

**Issue by barcamek** [WhiteMagic/JoystickGremlin#173]
Running JG on Win7 64bit as Admin.
The Crash occure everytime when I am trying to load any saved Profile. Tried R11 and later R11.1 with no changes. 

Thanks for the work on this great software.

Regards 
Marek 

[system.log](https://github.com/WhiteMagic/JoystickGremlin/files/2684029/system.log)
![jg_error](https://user-images.githubusercontent.com/45924668/50059773-7a924900-018b-11e9-811b-f0931ead827e.jpg)

**Comment by WhiteMagic** [comment]
Could you upload one of the profile that cause this? Are you by chance using non ASCII characters in descriptions or similar, or a non US keyboard layout? The latter shouldn't cause problems while the former is causing crashes like that though has since been fixed in the new version I'm working on.

**Comment by barcamek** [comment]
Here are the profiles that cause the crash.  I have a keyboard with a german layout but i am not using any special characters.
[Profiles.zip](https://github.com/WhiteMagic/JoystickGremlin/files/2687778/Profiles.zip)

**Comment by barcamek** [comment]
you are absolutely right. The problem seems to be a non ASCII in the Profile. My pedals are Logitech® Driving Force™ Pro Pedals. The name of the device ist written by the software to the profile with ® and ™. After deleting the non ASCII caraters i was able to load the profile.
Thank you for the hint.

**Comment by WhiteMagic** [comment]
That's good to hear as it means that the bug has already been squashed with #153 so with the next version you shouldn't have to edit the profile anymore as the XML will be written and read properly using UTF-8 encoding.
