### ISSUE TITLE
Generation of cheatsheet ignores "description" entries on basic HAT remap

### ISSUE THREAD

**Issue by robert914** [WhiteMagic/JoystickGremlin#187]
If I use the following mapping:

```
                <hat description="HAT: Shield Distribution, Scan Angle, UI Direction" id="1">
                    <container type="basic">
                        <action-set>
                            <description description="Up: v_shield_raise_level_forward, v_inc_ping_focus_angle, pc_screen_focus_up"/>
                            <description description="Right: v_shield_raise_level_right, pc_screen_focus_right"/>
                            <description description="Left: v_shield_raise_level_left, pc_screen_focus_left"/>
                            <description description="Down: v_shield_raise_level_back, v_dec_ping_focus_angle, pc_screen_focus_down"/>
                            <remap hat="1" vjoy="1"/>
                        </action-set>
                    </container>
                </hat>
```

When I generate a PDF cheatsheet, it does not output the above description entries at all. I looked at the code, and it appears that no additional description entries are output when it's a normal HAT mapping. It seems to only output information about bindings when you do a virtual button mapping. The current code in "cheatsheet.py" looks like:

```
        # If it's not a hat we have one input name and each description element
        # on a line of its own
        if self.input_item.input_type != gremlin.common.InputType.JoystickHat:
            additional_desc = ""
            for c_descs in container_desc:
                for a_desc in c_descs:
                    additional_desc += "\n{}".format(a_desc)

            if len(additional_desc) > 0:
                description += additional_desc
        else:
            # Single container with virtual button
            if container_count == 1 and containers[0].virtual_button:
                tmp = []
                for direction in containers[0].virtual_button.directions:
                    tmp.append("{} {}".format(
                        input_name,
                        hat_direction_abbrev[direction]
                    ))
                input_name = "\n".join(tmp)
```

There is a missing "else:" on the HAT section. I changed it to the following, and it will at least output my description entries now, but I'm not sure it's the cleanest / correct solution:

```
        # If it's not a hat we have one input name and each description element
        # on a line of its own
        if self.input_item.input_type != gremlin.common.InputType.JoystickHat:
            additional_desc = ""
            for c_descs in container_desc:
                for a_desc in c_descs:
                    additional_desc += "\n{}".format(a_desc)

            if len(additional_desc) > 0:
                description += additional_desc
        else:
            # Single container with virtual button
            if container_count == 1 and containers[0].virtual_button:
                tmp = []
                for direction in containers[0].virtual_button.directions:
                    tmp.append("{} {}".format(
                        input_name,
                        hat_direction_abbrev[direction]
                    ))
                input_name = "\n".join(tmp)
            else:
                additional_desc = ""
                for c_descs in container_desc:
                    for a_desc in c_descs:
                        additional_desc += "\n{}".format(a_desc)

                if len(additional_desc) > 0:
                    description += additional_desc
```

I can create a pull request if you want, but I wasn't sure this was the best solution to the problem.

**Comment by WhiteMagic** [comment]
I'll have to look into it, as the fact that I explicitly didn't want to handle hats seems to me that I may have wanted / anticipated to add something that would add the directions into the output or similar. Essentially possibly trying to avoid the users having to add the "up/down/etc" things themselves.

**Comment by robert914** [comment]
I'm not mapping anything explicitly, just the entire HAT from my real joystick to the vJoy joystick. I'm using the "description" entries to create documentation for myself as to what I have the HAT mapped to in the particular game binding file (since it's set to a specific HAT binding direction, not a virtual button).

Basically, I'm trying to build my binding "documentation" from Joystick Gremlin's Cheatsheet.

**Comment by WhiteMagic** [comment]
Yeah, I was more wondering why I was making a point to not include hats in that processing. As I've said I'll need to take a look at the code and see if I can figure out / remember what my reasoning / intention was. Though your change definitely would fix that issue, just not sure if I had some other weird idea going on while writing that code.

**Comment by robert914** [comment]
Yes, completely understand! That's why I wasn't sure if this was the best fix. It's working for me in the short-term with a modified version. Let me know if you need any testing or help.

**Comment by robert914** [comment]
Also, I am trying to locate where the title banner for each device is generated. It currently only shows the device name/type at the top. I'd like to be able to also have the "label" for the device shown in that banner as well (when defined).

**Comment by WhiteMagic** [comment]
That should be the DeviceFloat class which gets setup here https://github.com/WhiteMagic/JoystickGremlin/blob/develop/gremlin/cheatsheet.py#L308 To get the description of the device in there it probably would be cleanest to modify the DeviceFloat class to be provided the device object and then extract the data from there, as opposed to being provided the string as it is now.

**Comment by robert914** [comment]
Ah, there it is! Thanks.

**Comment by WhiteMagic** [comment]
Ok looking over the code there is a bit of fixing to do. As it stands currently it's going to be in general crappy when generating the text for hat related containers. The only time it will generate output is if you have exactly one container and it has a virtual button. So things like
- multiple basic containers
- hat to buttons
- multiple containers in general
- one container but without virtual button setup
are all not going to generate output. Not sure what my intent was with that there but the correct thing to do is to add proper handling of all these cases in the generator.

**Comment by robert914** [comment]
Thanks for looking into this. Let me know if I can be of assistance.

**Comment by WhiteMagic** [comment]
3900c5e6e95b514dcb8685641d5c302702890a2a implements proper pdf content generation for various hat inputs setups.
