### ISSUE TITLE
Not an issue, but a suggestion: Axis splitting

### ISSUE THREAD

**Issue by aka2k** [WhiteMagic/JoystickGremlin#19]
First and foremost, thanks for such an awesome piece of software. It's powerful, turned my Hotas X into a very decent joystick.

My suggestion: is it possible to add an axis splitting function just like Universal Joystick Remapper? Honestly, that's the only missing feature for Joystick Gremlin. 

Thanks again for the great job. Cheers, mate.

**Comment by WhiteMagic** [comment]
You can already do that, albeit using a script rather then the UI. An example which works on the T16000 can be found here: https://gist.github.com/WhiteMagic/964a6ad0d7df7c0ed521227783bf0138

You'll have to modify the t16000 variable to fit the hotas.x and adapt the axis vallues in the split_xaxis function to match what you need. Finally you'll have to place this modified code in a file that sits in the same folder as the profile for your stick and add it to the profile via the Tools -> Manage custom modules option.

If you need help feel free to send me an email at white.magic@gmx.de

I'll also have a look if there is an easy / sane way to add something like this to the UI.

**Comment by WhiteMagic** [comment]
Split axis implemented as a new plugin in 29e1545b7fac1dc5832ef83517ee77109f3e4bf4.
