### ISSUE TITLE
Can't install vjoy on recent Windows 10 builds - vjoy no longer supported by author

### ISSUE THREAD

**Issue by robled** [WhiteMagic/JoystickGremlin#193]
I know that this isn't a problem with Joystick Gremlin itself, so please forgive me, but I'd like to try this program since it does exactly what I want, however vjoy has a compatibility issue with recent builds of Windows 10 that I'm able to duplicate.  The issue has been [reported ](https://github.com/shauleiz/vJoy/issues/24)upstream, and unfortunately is unlikely to be resolved anytime soon since the author of vjoy is [not supporting](https://github.com/shauleiz/vJoy/issues/23#issuecomment-441392026) it anymore.

I'm curious if any other Joystick Gremlin users have run into this issue and have a work-around, or if Joystick Gremlin can be made to work with another dependency that can run on recent builds of Windows 10.

**Comment by WhiteMagic** [comment]
I haven't run into this, but also haven't reinstalled my windows install from scratch in a while. I'm not aware of any suitable replacement for vJoy. Vigem is the only other tool like it that I know of which is being worked on and that is only an alternative and not a replacement as it is designed to emulate xbox and ps3 gamepads which aren't remotely sufficient input wise.

**Comment by laurentand** [comment]
vjoy installed recently on a w10 latest build. No pb here.

**Comment by aka2k** [comment]
> 
> 
> vjoy installed recently on a w10 latest build. No pb here.

You might be the only one with a working vjoy copy. I have even installed the driver on the Windows build 1703 and found it broke after updating to 1903 Windows.

**Comment by bluddy** [comment]
I'm having a similar issue. vJoy initially said it was installed, but didn't do a sufficient installation. Later installs attempts fail.

**Comment by bluddy** [comment]
Correction: now found the newest version of vjoy from github, and it works great.
