### ISSUE TITLE
Uncaught Exception: create_input_dropown: list out of index

### ISSUE THREAD

**Issue by JoeSchr** [WhiteMagic/JoystickGremlin#195]
Hi,
I got a few exception lately.  This was the last one I happen to catch: 
![image](https://user-images.githubusercontent.com/8218910/53301134-4ef8a280-384f-11e9-8e95-c3ee4e5b5d0b.png)

Gremlin still keeps running and working in the background though, so probably no high priority.

**Comment by WhiteMagic** [comment]
This sounds like the same underlying issue as #189, i.e. your vjoy device lacks an input such as a hat and when adding a remap action to a hat Gremlin will attempt to select a hat by default which would then fail in this manner.

**Comment by JoeSchr** [comment]
But I have 2 HATs configured, haven't I?
![image](https://user-images.githubusercontent.com/8218910/53337948-b58ac880-3902-11e9-9ec2-4693cbef7708.png)

**Comment by WhiteMagic** [comment]
Yeah based on that you have. The hat case was more of an example of where Gremlin typically assumes something exists but can't find it. There probably are other cases like a profile containing a map to hat 3 when there is no hat 3 present. Essentially I just need to check whether or not what Gremlin wants to select exists before telling the UI code to do something.

**Comment by WhiteMagic** [comment]
89ce4ba0a4edfc90bf92a3382d01f7c8c9bbff95 should hopefully prevent this from occurring in the future.

**Comment by JoeSchr** [comment]
thank you!
