### ISSUE TITLE
Virtual axis won't go over 99%

### ISSUE THREAD

**Issue by Ottomic** [WhiteMagic/JoystickGremlin#201]
I'm not sure whether this is a problem with vjoy or JG but for some reason none of my virtual axes won't go past 99%. They go down to -100%, but this upper 1% can't be achieved. Joystick shows 100%, and it doesn't matter if it's a 1:1 map or a bezier curve. Any ideas as to what might cause that and how to solve it?

**Comment by WhiteMagic** [comment]
Hmm that sounds rather odd, there are two things I can think of right now that might cause this.

If the physical stick reports odd values that Gremlin misreads or doesn't expect this could cause this. The other option is that the calibration expects a higher value then you ever generate with the physical device and thus Gremlin will produce values below 100%.

You can use diview (http://www.leobodnar.com/files/DIView.zip) to see the raw data sent by the devices, which might give us a clue if one of these two ideas applies or if there is something else going on.

**Comment by NdranC** [comment]
I have this exact same issue. I downloaded DiView and it is reported accurately as 100% (65535) on both my T.16000M and vJoy. Could this be just a visual glitch with the Imput Viewer?

**Comment by WhiteMagic** [comment]
I had a look and fixed it with baa75dfc81f73d44d4f0bb5e9c29bc8169c5e8f3. This was purely a display bug caused by not rounding values properly.
