### ISSUE TITLE
Joystick Condition no longer accepted in Release 13

### ISSUE THREAD

**Issue by Paddy-van-CH** [WhiteMagic/JoystickGremlin#204]
I'm remapping two different physical joystick axis to the same vJoy virtual axis and use a switch on the joystick to select between the two. 
With release 13 the joystick condition is no longer respected. I.e. same set-up as in release 12, flicking the switch does no longer allow to switch between the axis.

Workaround: Remapping the switch to a virtual vJoy button and setting up a vJoy condition.

Setup: VPC Mongoos T-50.
Mapping physical axis Z and X-Rotation to vJoy Y-Axis. 
Utilizing physical switch T2 (on/off switch) to dynamically allocate Z or x-rot to vJoy y.

**Comment by WhiteMagic** [comment]
I quickly tried this and this works using Joystick Conditions for the button to swap between which axis is to be used. If the profile was converted from R12 then I think Gremlin might not have been able to figure out which device it should listen to, as conditions previously used the windows ID which has no meaning anymore.

Try rebinding the button in the condition to set the guid, now used by Gremlin, properly. I have only tested this with a T16000 so maybe there is something off with Gremlin reading the state of the buttons on the T-50. You can check that in the Input Viewer, if Gremlin fails to show the state of the buttons properly then that is an issue that needs fixing.

**Comment by Paddy-van-CH** [comment]
Input Viewer does show the correct state of the switch and does also record the input state of the axis. Rebinding the joystick condition did not resolve the issue.
Mapping a button from another joystick did work. 
It looks like there is an issue in reading buttons from the T-50. Anything greater than button 7 will not register for the joystick condition.

**Comment by WhiteMagic** [comment]
Ok that is really odd then. If Gremlin's input viewer show the correct state of buttons and sees them being pressed and released then everything inside of Gremlin should see that as well. I'll have to look into the condition code to see if I'm doing something odd there that got broken by moving away from SDL2.

**Comment by WhiteMagic** [comment]
Can you grab this example program https://github.com/WhiteMagic/dill/releases/download/v1.1/dill_v1.1.zip which uses the same input library as Gremlin. It should see all your devices and report input events.

For one all the inputs should be seen, including buttons > 7. Also if you afterwards could look at the debug.txt file it creates and see if there is anything that looks off in there. Some errors are expected, for example:
```
[2019-04-10 21:16:01.625] [debug] [info] {750832F0-B232-11E7-8008-444553540000}: Processing device: CH PRO PEDALS USB 
[2019-04-10 21:16:01.626] [debug] [error] {750832F0-B232-11E7-8008-444553540000}: Attempted to read buffered device data from a device that is not buffered. (DIERR_NOTBUFFERED)
[2019-04-10 21:16:01.626] [debug] [error] {750832F0-B232-11E7-8008-444553540000} Failed reading device in buffered mode, falling back to polling, Attempted to read buffered device data from a device that is not buffered. (DIERR_NOTBUFFERED)
```
Is harmless, as this is the library switching from buffered to polled device handling and is normal behaviour.

**Comment by Paddy-van-CH** [comment]
[debug_defect.txt](https://github.com/WhiteMagic/JoystickGremlin/files/3064225/debug_defect.txt)
[debug_worked.txt](https://github.com/WhiteMagic/JoystickGremlin/files/3064226/debug_worked.txt)

**Comment by Paddy-van-CH** [comment]
I've attached the two debug files. 
(Sorry for pressing the wrong button and closing the subject.)

"_defect" is where a button with id > 7 is picked. "_worked" is with button id 1.

**Comment by WhiteMagic** [comment]
I just managed to reproduce the issue you're having, so that's good because it means there is just some logic inside Gremlin that's messed up and not something that's specific to any particular device which would be way harder to debug.

I still have to actually find what's wrong but given I can reproduce this that shouldn't be terribly hard.

**Comment by WhiteMagic** [comment]
You can give this one a go, that should (tm) fix the problem https://www.dropbox.com/s/vfslyyee9df8i2u/Joystick.Gremlin.R13.1b2.zip?dl=1

**Comment by Paddy-van-CH** [comment]
Sorry to disappoint, still the same behavior.

**Comment by WhiteMagic** [comment]
That was me posting on the wrong issue ... that fixes another issue (hopefully) haven't gotten to the condition one yet

**Comment by WhiteMagic** [comment]
If you download the version from the above link again it should now work (I just updated the zip in place)

**Comment by Paddy-van-CH** [comment]
Problem solved. Thank you very much.

**Comment by WhiteMagic** [comment]
Cool, so 8fb1080c66752e30386d3795f3ab73676fc5c0a2 actually worked.
