### ISSUE TITLE
Program doesn't run or crash if I connect MJOY16 board

### ISSUE THREAD

**Issue by Forsaken-Player** [WhiteMagic/JoystickGremlin#211]
Hello, I'm trying to use this software with the MJOY16 board that has 128 buttons and 8 axis. But it fails to initialize. If I connect the board with the app running this happens 

![image](https://user-images.githubusercontent.com/13246441/56450163-ac621a80-62f9-11e9-8a05-f9878a956562.png)

**Comment by Forsaken-Player** [comment]
This happens if I run the app with the board connected : 
![image](https://user-images.githubusercontent.com/13246441/56450177-0fec4800-62fa-11e9-829c-832383f0e488.png)

**Comment by Forsaken-Player** [comment]
[debug.txt](https://github.com/WhiteMagic/JoystickGremlin/files/3099683/debug.txt)

**Comment by WhiteMagic** [comment]
The cause of the error is the same as in #210 in the sense that Gremlin tries to access the same information in all cases but fails because it isn't there. The underlying issue for that looks like it might be in DILL, the library I've written to handle input, so I'll have to take a look at that one to figure out why the errors you're getting are occurring.

**Comment by WhiteMagic** [comment]
I've added some more debug information to DILL which handles all the input, this should print the information it extracts for the devices in the debug.log file, which hopefully can tell us if DILL is getting the information wrong or if it's something to do with how I read that information with Gremlin.

If you download the zip file and extract the dill.dll file and use it to replace the existing one in your Gremlin folder the debug.log should hold some additional "Device Summary" information.

[dill.zip](https://github.com/WhiteMagic/JoystickGremlin/files/3100824/dill.zip)

**Comment by Forsaken-Player** [comment]
Hello!!, I've tried with this dill.dll new file...
With MJOY16 board connected I get this at program start.
![image](https://user-images.githubusercontent.com/13246441/56470528-77e77f00-641d-11e9-8bff-8a70a3f5e6a9.png)

And this with the program already running : 
![image](https://user-images.githubusercontent.com/13246441/56470866-a49d9580-6421-11e9-8fb2-15d54fa75dce.png)
[debug1.txt](https://github.com/WhiteMagic/JoystickGremlin/files/3101237/debug1.txt)
[debug.txt](https://github.com/WhiteMagic/JoystickGremlin/files/3101238/debug.txt)

**Comment by WhiteMagic** [comment]
Ok that helped, I now know why Gremlin is so unhappy and is causing the above error.
```[2019-04-21 10:40:16.019] [debug] [info] Axis=9 Buttons=112 Hats=1```
This should not ever exist, a DirectInput device cannot have more then 8 axes so either the MJoy is reporting something odd, or more likely, I have something in my code that's getting confused and is reporting a wrong value.

The quick and dirty fix which I will do in a bit is to change the library to not ever allow a value greater then 8 which hopefully should fix the issue but not solve the root cause but at least Gremlin should behave.

**Comment by WhiteMagic** [comment]
Ok you can give this dll a go. It should prevent the axis count to be invalid and show warnings about that in the log but only report 8 axes and list the 8 you have. This should fix it but I can't really test this as I don't have a device which causes these issues here.

[dill.zip](https://github.com/WhiteMagic/JoystickGremlin/files/3101999/dill.zip)

**Comment by Forsaken-Player** [comment]
Success!!! I'll try later if it works... 
But at first try it didn't crash! :D
![image](https://user-images.githubusercontent.com/13246441/56488933-669e8100-64b6-11e9-9612-e878f8f3f54a.png)
Thank you!
[debug.txt](https://github.com/WhiteMagic/JoystickGremlin/files/3102577/debug.txt)

**Comment by Forsaken-Player** [comment]
Testing... works! and it does the function I was needing. (hidding the device) :D

What I do miss is the ability of doing an ON-ON switch I can do in UCR. Or maybe I couldn't do it since it's my first time using Joystick_gremlin. So far it's a super great app with tons of potential! 
Thank you for your software!

Pd: In UCR I use this config to achieve ON-ON switch. This way I can get 2 button presses with only one input. For example if I press (rocker switch On-off) mjoy16 button 57 it activates **button 5 in vjoy** and if I turn off the switch it would **activate button 6 in vjoy**
![image](https://user-images.githubusercontent.com/13246441/56490933-3e665080-64bd-11e9-99d9-52be8b2d9f5c.png)

**Comment by WhiteMagic** [comment]
That's good to hear that the updated library works. If all you need is to hide devices via HidGuardian you probably could also use HidCerberus which creates a webinterface to do that, Gremlin doesn't do anything more then setting a few registry entries that HidGuardian uses.

For the on-on switch I think you should be able to get that working using two macros and conditions on them.
```
Macro 1
- press vJoy button 5
- release vJoy button 6
Condition on Macro 1:
- run when mjoy16 button 57 is pressed

Macro 2
- release vJoy button 5
- rpress vJoy button 6
Condition on Macro 2:
- run when mjoy16 button 57 is released
```

**Comment by Forsaken-Player** [comment]
Thank you for your advice. I've tried HidGuardian but it didn't let me select the Falcon BMS... I might try again later. Still I prefer your solution since it's all integrated in one app. If that macros work it will make things great for me. 

Thank you again!
