### ISSUE TITLE
Wireless Xbox one (bluetooth) only emulates vjoy if Joystick Gremlin has focus

### ISSUE THREAD

**Issue by GameOverture** [WhiteMagic/JoystickGremlin#216]
_In regards to an Xbox One controller, connected via a Bluetooth receiver:
(Windows and Joystick Gremlin identify this controller as: "Bluetooth XINPUT compatible input device"_

If you open some vJoy monitoring software (like vJoy Monitor or Joystick Gremlin's Input Viewer) and then focus some window other that any of Joystick Gremlin's, no inputs will be shown.

If Joystick Gremlin, or any of its child windows has focus then vJoy inputs will be seen in these monitoring programs.

**Comment by WhiteMagic** [comment]
This sounds really odd, as there is nothing special about a bluetooth connected device or xbox controller as far as Gremlin is concerned. Though since I have one of those lying around I should be able to see if I can get my system to behave the same.

**Comment by GameOverture** [comment]
I think it might have to do with the controller being recognized as XINPUT rather than DirectInput, and perhaps dill handles that differently than SDL2.

**Comment by WhiteMagic** [comment]
If the device was only exposing an xinput interface then dill would not be able to see it at all so focus or lack thereof shouldn't impact this. I don't remember if sdl2 does some kind of fake directinput on xinput devices, it's been a while that I looked at the code. Though in the end I just have to find some time to play with it to see what's going on.

**Comment by WhiteMagic** [comment]
So the thing gets even weirder that Gremlin can receive input as you've observed, however, the dill test application can't see anything. So this clearly is a problem but it's on dill's end so I'll move that issue over there. https://github.com/WhiteMagic/dill/issues/1
