### ISSUE TITLE
FFB Support?

### ISSUE THREAD

**Issue by TehNewbie** [WhiteMagic/JoystickGremlin#218]
Hello there! Not really an issue, more of a question (I hope you don't mind). Do you have any plans for Force Feedback support? I'm asking out of curiosity, since I have seen only one vJoy mapper with FFB support so far, and it's made for SCP Driver (which in turn is for DualShock controllers).

If such a feature were added, your program could act like a complete XInput to DirectInput converter, so to say. Again, I'm asking out of pure curiosity, haha :smile:

**Comment by WhiteMagic** [comment]
I haven't really looked into anything FFB related, so while technically not out of the question it's also not something that currently is on my radar to be looked at. So if I ever get around to doing something like this it most likely won't be any time soon.

**Comment by TehNewbie** [comment]
I see, thanks for answering. Keep up the fine work! :+1:

**Comment by cyberluke** [comment]
FFB is DirectX since Windows 98
