### ISSUE TITLE
vJoy not compatible with Windows 10 1903

### ISSUE THREAD

**Issue by Carlton2001** [WhiteMagic/JoystickGremlin#219]
Hi,

vJoy is not compatible with Windows 1903 and it is no more supported since last year.
How do you see JG's future ? Are you already working for a workaround or on another virtual device provider ?

**Comment by Carlton2001** [comment]
Sorry, didn't see issue #193 but I can confirm that vJoy is not longer usable past Windows 1809.
Lots of posts about this in the vJoy forum also.

#sadface

**Comment by WhiteMagic** [comment]
Not really something I am doing anything about at this time. Writing drivers is an entirely different beast from interfacing with existing C libraries and I currently don't have anywhere near enough time to work on something like that. I'm also not sure how widespread the issue is, it obviously exists and is annoying as hell for those that are affected by it.

The only other input emulation driver I know of is vigem, but that is doing xinput devices which supports a fraction of the inputs a proper directinput can support, so sadly it's not really an option.

**Comment by djscott00** [comment]
This thread is worth following: https://github.com/shauleiz/vJoy/issues/23#issuecomment-497945362

Sounds like there may eventually be a fix in place as another user (weeryan17) is able to update vJoy, and then he has someone to help with digitally signing the updated driver.

**Comment by muchimi** [comment]
Current workaround: run windows 10 1903 in test mode and use the version R.T.B. put together here:

https://github.com/R-T-B/vJoy/releases

He indicated he's getting a certificate to sign the driver so that Windows will accept it.

**Comment by WhiteMagic** [comment]
Just as a reminder, if you decide to run Windows in test mode be sure you know what this implies and if the associated risks are worth it.

**Comment by Carlton2001** [comment]
Signed and working version here (v2.1.9.1)
https://github.com/jshafer817/vJoy/releases

**Comment by Carlton2001** [comment]
JG R13.2 is not ok to run a profile with this new vJoy version :

` ERROR Failed accessing vJoy id=1, error is: 'Running incompatible vJoy version, 2.1.8 required'`

**Comment by muchimi** [comment]
You can download the source code and make the change yourself - the source code to change is on line 479 of the /vjoy/vjoy.py source file.  Change it to whatever the signed DLL is - 0x219 is the USHORT required in this case.  I don't think this will cause issues as 2.1.8 is probably not that different from 2.1.9.

**Comment by muchimi** [comment]
Update - got it working using 0x219 as the version code without test mode!

I'm still battling python to build me an exe that will load - probably some path issue - but I have it working temporarily including under HIDGuardian on Windows 10 without test mode enabled ! 

I also noted that reportlab is a dependency - you need to pip install reportlab or nothing will work.  32 bit python only or nothing works either.  I'm running it on python 3.7.4 32 bit.

**Comment by WhiteMagic** [comment]
Give this version a go https://github.com/WhiteMagic/JoystickGremlin/releases/download/Release_13.3/Joystick.Gremlin.R13.3.zip that should accept any vjoy version newer then 2.1.8

**Comment by muchimi** [comment]
Works like a champ, thank you.  What a goat rodeo this windows update was.

**Comment by WhiteMagic** [comment]
Good to hear that this works, none of my windows machines had the pleasure to get updated so I had no need to any of the recompiled and signed vjoy variants and thus couldn't truly test if the change would work properly.

**Comment by Carlton2001** [comment]
Thanks WhiteMagic, you are the best.
You can force update your Win 10 here : https://www.microsoft.com/en-us/software-download/windows10
