### ISSUE TITLE
Where is the Profile Creator

### ISSUE THREAD

**Issue by monsoontm** [WhiteMagic/JoystickGremlin#221]
In the online manual there is the section of profile creator but I have no idea where it is in program. Has it been removed? Thanks

**Comment by WhiteMagic** [comment]
The tool has changed name at some point, it lives under File -> Modify Profile, which is a better name for what it does. It effectively allows using an existing profile and bind the actions defined within to the physical inputs of devices present on the machine.

**Comment by monsoontm** [comment]
Gotcha. But how do I get that screen to pop up as indicated on the online manual? thanks

**Comment by WhiteMagic** [comment]
Ah yeah you have to load a profile via it, but yeah it's unlikely to work if a profile is broken but it also probably doesn't tell you that it failed because of that.
