### ISSUE TITLE
Failed parsing GUID from value 0'

### ISSUE THREAD

**Issue by Camisade** [WhiteMagic/JoystickGremlin#226]
Yesterday, after changing profiles, I tried to change back to the first one and began receiving the error:
------------------------
Failed to load the profile <full pathname> due to:

'Failed parsing GUID from value 0'
------------------------

This happened under r13.2, but it's still a problem under r13.3.

I've looked through the xml, but can't find any differences between "working" profiles and the one that's causing this error. I'd really like to just be able to correct the faulty xml file rather than rebuilding the profile from scratch.  Any ideas why I suddenly began getting this error?

I have not otherwise done any editing of the xml files outside of Joystick Gremlin.

I *think* that before I exited the first profile, I got the message that I'd made changes, was asked if I wanted to save the changes, and I indicated yes. So the problem may have been introduced if JG didn't properly save the changes for some reason.

Attached are the profile that apparently got corrupted when I switched away from it (frags.xml) and an example of a working one (multi-cannons.xml) -- note that the .xml has been renamed to .txt to meet file type submission requirements
[frags.txt](https://github.com/WhiteMagic/JoystickGremlin/files/3417960/frags.txt)
[multi-cannons.txt](https://github.com/WhiteMagic/JoystickGremlin/files/3417961/multi-cannons.txt)

.

**Comment by WhiteMagic** [comment]
In line 390 there is a joystick entry in a macro which has as guid of 0. This could have been caused by a conversion or manually adding a joystick action and then not assigning a joystick to it by pressing the button intended to be pressed. Removing that line should make Gremlin not complain about the profile.

I'm not sure if you intend to have a physical joystick event there. If you do then you will have to press the button in the UI to assign the physical input. However, this will not emit a physical event that programs outside Gremlin can see. Gremlin will see a "fake" physical input and will handle it but no program outside of it will.

**Comment by Camisade** [comment]
Thank you! That did it.  ...now the (idle) question I have is: What might I have done within the Joystick Gremlin UI that created/changed that profile to create the error-creating entry?

Please don't feel obligated to answer that question -- your time is valuable. I just like to identify "things to avoid" to prevent re-creating this problem down the line, because I do tweak these profiles (within JG) from time to time and I can't think of what I might have done to this profile other than deleting a single button press in a keyboard macro assigned to a joystick button...  Anyway, thanks again!

**Comment by WhiteMagic** [comment]
I can't say for sure how this happened, but the two ways I could think of are:

1. The profile hadn't been loaded in R13 yet and as such was converted and the conversion code has a bug where it doesn't deal properly with converting joystick macro entries.
1. Somehow you managed to change on macro entry to a joystick, for example via the dropdown menu, and that defaults to an invalid state (which is something I should fix)

There probably are other ways that could explain how this happened but it's not really easy to say what exactly happened or how to prevent it. In the end Gremlin should handle such things more gracefully.
