### ISSUE TITLE
only certain callbacks work for a particular stick

### ISSUE THREAD

**Issue by muchimi** [WhiteMagic/JoystickGremlin#247]
Having a weird problem with this code:

```
import gremlin

T16K_NAME = "T.16000M"
T16K_GUID = "{A60B5E20-25E9-11E7-8002-444553540000}"
MODE_ALL = "Default"
t16k = gremlin.input_devices.JoystickDecorator( T16K_NAME, T16K_GUID , MODE_ALL )

@t16k.axis(1)
def a1(event, joy, vjoy):
	gremlin.util.log("test 1")
	
	
@t16k.axis(2)
def a2(event, vjoy):
	gremlin.util.log("test 2")

@t16k.axis(3)
def a3(event, vjoy):
	gremlin.util.log("test 3")	
	
@t16k.axis(4)
def a4(event, vjoy):
	gremlin.util.log("test 4")
```

The T16K stick has 4 axes.  However in the above code, axis(3) and axis(4) are not triggering the callbacks when the axes are moved (twist and throttle respectively).  axis(1) and axis(2) work as advertised - so the "test 1" and "test 2" are showing in the log, but "test 3" and "test 4" never show.

Any clue as to what I'm doing wrong?

Thanks!

**Comment by muchimi** [comment]
Problem solved:  turns out that the axes, while there are 4, are not in sequence (1..4), but rather on the T16K come out at 1,2,6,7.   So the index number is really not an index number but looks like an enum, with 6 being the rudder, and 7 being the first slider.

I was expecting them to be sequential - they are not.  Works now!

**Comment by WhiteMagic** [comment]
They used to be sequential, however, devices are actually not required to use them sequentially and many do not. The callback treats the number as the identifier, which for buttons and hats is just the linear index, but for axes it's their numerical name so to speak.

This makes the way how axis ids work identical to how vJoy axis are used in Gremlin, which is a bit more consistent. The main reason to not have them sequential anymore is that joy.cpl etc. actually show axis by their names and thus use the name associated with the identifiers. I'll have to double check if the axis names that exists as an enum in Gremlin could actually be used here, that way it would be clearer that they are identifiers rather then linear indices.

**Comment by muchimi** [comment]
The sequence (at least for this particular stick) was showing names that weren't sequential in the input dialog (that shows what Gremlin detected and current axis values by name).  Except I didn't realize that immediately at first look.   Eventually it hit me that the names went from x axis, y axis straight to z rotation.  That's how I deduced it was not sequential because the z-rotation was #6 in the enum, and the slider was #7.    I think it would be good to add that to the plugin docs in the JOY section that (1) the index is not sequential and (2) here's the lookup table by name.  Perhaps adding the actual index number in the input dialog would help so the user gets not only the name, but the corresponding index number as well.   Looking at the input source, I totally get how they are not sequential, but I think the examples, perhaps older, certainly didn't guide me there to start with.   

Now that I know how it works - it works really well.

**Comment by WhiteMagic** [comment]
Yeah the docs always can do with improvements, some portions of it are likely to be out of date by now, especially in the more technical parts.
