### ISSUE TITLE
delete a condition (minor or irrelevant or no bugs)

### ISSUE THREAD

**Issue by Francky63** [WhiteMagic/JoystickGremlin#255]
When a condition is set to 'none'  it remain the empty row for activation
`<activation-condition rule="all"/>`

**Comment by WhiteMagic** [comment]
I'd have to look into this but should not cause any issues. Though given R14 will change all those things that part of the profile XML will probably be redone anyways.

**Comment by WhiteMagic** [comment]
I had a look through the code to check what will happen with those entries. They are fine, as that's what Gremlin internally generates on its own for an empty condition.
