### ISSUE TITLE
Joystick Gremlin - Error. 

### ISSUE THREAD

**Issue by BeradedGelfling** [WhiteMagic/JoystickGremlin#259]
Hi, I've been having an issue with Joystick Gremlin on and off for a while now. Where I would need to restart my PC to get it to boot correctly - it would sometimes get stuck booting up but not lunch. A reset of my PC would fix this...

However, I am now unable to get Joystick Gremlin with dual Thrustmaster T16000's to launch at all and I am getting an error message as seen below...

Uncaught exception:
Traceback (most recent call last):
   File ''joystick_gremlin.py'', 1269 in <module>
   File ''gremlin\joystick_handling.py, line 250, in joystick_device_initialization
 gremlin.error.GremlinError: 'Indistinguishable vJoy device present.\n\nvJoy devices have to differ in the number of (at least one of) axes, buttons, or hats in order to work properly with Joystick Gremlin.'

**Comment by WhiteMagic** [comment]
Based on the error it seems that you have two or more vJoy devices configured and that at least two have the exact same number of axes, buttons, and hats. If that's the case you have to change, for example, the number of buttons on those identically configured devices so that Gremlin can tell them apart.

**Comment by BeradedGelfling** [comment]
Odd I only have one listed in the drivers. Is there a way to reset vJoy so that I can start again with just the one?

I did notice in vJoy config list thing - that I have 2 'profiles' as it where listed... but I can only see one 
via windows.

**Comment by BeradedGelfling** [comment]
Ok worked out how to reset vJoy back to default and only using own 'profile' seem to be working again. Thank for the insight into the issue gave me much needed direction to resolve this issue. 

Able to fly in Star Citizen again thank you o7

**Comment by WhiteMagic** [comment]
Good to hear. And it sounds like there was some fun with vJoy reporting more then one device or Gremlin somehow managing to see more then one.
