### ISSUE TITLE
Template system for easier config sharing

### ISSUE THREAD

**Issue by WhiteMagic** [WhiteMagic/JoystickGremlin#26]
Implement a system which allows rebinding existing configurations onto new devices, it should allow the following:
  * use plan XML profiles
  * present a view which shows actions by mode
  * allow users to press / move / etc the desired input once an action has been selected to bind this
  * store the final result as a new profile

**Comment by Pretagonist** [comment]
This is probably beyond the scope of your wonderful app but my dream is a system where I download a file (say xml) with all the available binds for a game including instructions for generating a config file specific to that game. I'm then presented with a center panel with all the possible keys for the game and surrounding this are images representing my controllers. I could then drag and drop actions onto my controllers.

**Comment by WhiteMagic** [comment]
It's a bit too much for right now but I've had similar thoughts in the past. Though at least the part about downloading a XML file and then seeing all the available actions and binding them is what this feature is about. You wouldn't see a nice graphical representation of your device but you'd press the desired input for the specific action.

The bit about generating an actual game config file is outside the scope of this feature for right now, but an idea would be to have a XML file which has the default mapping of a game and then there shouldn't be a need to create a specifically tailored configuration. Though as I said, I have though of this and who knows what I end up implementing down the road :-)

**Comment by WhiteMagic** [comment]
Initial version implemented with 7999143499c303399d95029e258f2354373d6a81.
