### ISSUE TITLE
Request or Solution: Zeroing out an axis on button release (better differential braking)

### ISSUE THREAD

**Issue by mnmean** [WhiteMagic/JoystickGremlin#265]
First question: 
Is there a way to zero out an axis on the release of a button? 

Context: 
I have a pair of VKB T-Rudder pedals; they're great pedals, but they do lack toe brakes. Toe brakes are traditionally two separate axes reflecting how much pressure is being put on each wheel ... useful for turning on the ground. 

Usually what I do is just map three buttons for the brakes -- left, right, both. If you're thinking "this would be a great use for split axis," we're on the same page. So now I have it set up so when the button is pressed, the rudder axis is split into left and right toe brakes (as well as still controlling the rudder). 

The only problem is as soon as I let go of the button, the toe brake axes remain as they are. In order to cancel out the brakes, I have to center the rudder, zeroing out the brakes, then release the button. I can, unless I'm mindful, get stuck in a situation where the brakes are locked in one direction or another. 

Maybe there's a way to do this already?
---
Second question: Is there a way to have a condition continuously monitored, so that a change in the condition could cancel the action? 

Context: Some sim planes seem designed with my T-Rudder in mind. Applying the brake button will apply full brakes if the rudder is centered, or differential brakes if rudder is being applied. The button can be held and will transition from left brake, to full brake, to  right brake as the rudder moves. 

Currently, I can set up a button to be full brakes if the condition of the rudder is neutral. But when I move out of neutral, the button remains on because the test has already been passed. Having the condition be continuously monitored would allow one button to fully control the brakes in conjunction with a single axis; and that would be pretty cool. 

---

Thanks for any help. This is an absolutely great program!

**Comment by WhiteMagic** [comment]
You should be able to reset the toe break axis with a macro that only triggers when the button you're using is released. The macro would only have to set the vJoy axis values to 0.

As for continuously monitoring a condition, no that is not possible as they are not behaving in that manner. The condition is only an additional check on actions that will be triggered via a physical input and filter out some actions associated with the physical input. However, you might be able to get the behavior you're after by using virtual axis buttons on the different axis ranges. So pressing/releasing buttons depending on the deflection of the pedal.

**Comment by muchimi** [comment]
There is an easy way to do that from a custom Python script.
You just listen for the release event and then set the button (or axis) on VJOY whatever you need it to be.   Much faster than dealing with UI based macros in Gremlin. 

```
@mydevice.button(3)
def my_function(event, vjoy):
  if  event.is_pressed:  # button is pressed
     vjoy[1].axis(3).value = 1.0  # full right
 else:
     vjoy[1].axis(3).value = 0.0  # center


```

**Comment by mnmean** [comment]
Thank  you guys, I'm almost there. 
Magic - I have a macro set to zero the axis on the condition a  button is released, but I'm not sure what would trigger the event? I could set up a bunch of axis buttons and have them continually run the test to reset? 

muchimi - What file do I drop my own script into? I know a little python, but not sure how it all works with Gremlin.

**Comment by muchimi** [comment]
@mnmean Recommend you start with the documentation here:

https://whitemagic.github.io/JoystickGremlin/user_plugins/

**Comment by WhiteMagic** [comment]
@mnmean In Gremlin's current setup conditions are checked only when the physical input they are associated with, e.g. axis, button, etc, changes state. So if the macro is configured on physical button 4 then only when that button is pressed or released will Gremlin check if the condition is met and if so execute the action.

As for documentation, the link above is potentially out of date as I'm pretty sure I haven't updated it for all the latest changes. If you wanted to write custom plugins then these ones https://whitemagic.github.io/JoystickGremlin/user_plugins_code/ are a good starting point as would be the 6 most recent ones on this page https://gist.github.com/WhiteMagic Though for simply resetting an axis to 0 when a button is released a macro with an action condition set to release should be all that is needed.

I'll post screenshots of an example later today, that way we can figure out if that is sufficient for your purpose or something more is needed.

**Comment by WhiteMagic** [comment]
I'm not sure if this will work for the setup you want. The setup does the following:
1. If the rudder is center vJoy button 1 is pressed, once the rudder is no longer centered outside of -0.1 and 0.1 the button will be released
2. Outside the center area the standard axis remap will be used.

If this goes kind of the direction of what you need there is probably a few things we can do to refine and integrate it better.

![bandicam 2019-12-08 23-41-29-777](https://user-images.githubusercontent.com/5612/70397657-71416280-1a14-11ea-8120-67a85f70b103.png)
![bandicam 2019-12-08 23-41-35-451](https://user-images.githubusercontent.com/5612/70397659-72728f80-1a14-11ea-944c-e35aeb0eba02.png)
