### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by matjam** [WhiteMagic/JoystickGremlin#267]
Receiving the following error when activating:

```
2019-12-16 22:06:31      ERROR Uncaught exception:
Traceback (most recent call last):
   File "gremlin\code_runner.py", line 343, in mode_changed
 IndexError: list index out of range
```

XML configuration:
[Elite Dangerous.txt](https://github.com/WhiteMagic/JoystickGremlin/files/3971663/Elite.Dangerous.txt)

I'm not changing modes or anything. Any ideas? Started happening trying to add response curves.

**Comment by matjam** [comment]
was able to resolve this by removing empty "Basic" containers in the vJoy entries.

**Comment by WhiteMagic** [comment]
Yep, empty containers seem to be the main cause of this type of error. It's likely that the next version won't suffer from this, due to all the reworks happening.
