### ISSUE TITLE
Macro Condition ALWAYS reverting to Pressed instead Released

### ISSUE THREAD

**Issue by joaogubert** [WhiteMagic/JoystickGremlin#269]
Please, see the video below. 
The option always revert to pressed state, but i want to use Released.

https://www.dropbox.com/s/u83qini2a6l57b0/IMG_5218.MOV?dl=0
@WhiteMagic

**Comment by BenBlake79** [comment]
You have to use "action condition" to make it dependent on wether your button is pressed or released. "vjoy condition" is used for a button pressed (as shift) or something like this. Took me a while to find this out as well...

**Comment by WhiteMagic** [comment]
Give this version a go https://github.com/WhiteMagic/JoystickGremlin/releases/tag/Release_13.3_debug I seem to have fixed the problem in that one. From memory for certain condition types the value was not being stored correctly in the profile.

**Comment by joaogubert** [comment]
Hello @WhiteMagic , 

Sorry for my delay, I was on vacation.
I've tested this version here, and now seems ok!!!

Thanks for your help!!!! :)

**Comment by WhiteMagic** [comment]
No problem, I hope your holidays were relaxing. Also good to see that the bug actually is fixed since it was kind of an annoying one as it impacted a rather commonly used function.
