### ISSUE TITLE
Pulse BUTTON

### ISSUE THREAD

**Issue by fdallera** [WhiteMagic/JoystickGremlin#283]
As from this old closed issue 
[(https://github.com/WhiteMagic/JoystickGremlin/issues/56)] 
i tried to setup a pulse button with a macro but i doesn't work ... what it happen is that as soon as i press the putton it start to pulse but when the button i released it doesn't stop and it continue until JG is stopped
this is the XML
```
                <button description="" id="25">
                    <container activate-on="release" delay="0.5" type="tempo">
                        <action-set>
                            <noop/>
                        </action-set>
                        <action-set>
                            <macro>
                                <properties>
                                    <repeat delay="0.1" type="hold"/>
                                </properties>
                                <actions>
                                    <vjoy input-id="5" input-type="button" value="True" vjoy-id="1"/>
                                    <pause duration="0.1"/>
                                    <vjoy input-id="5" input-type="button" value="False" vjoy-id="1"/>
                                </actions>
                            </macro>
                        </action-set>
                    </container>
                </button>
```
 this is a new profile with only this action

**Comment by WhiteMagic** [comment]
Just tried reproducing this to see if this is just something that misbehaves when combined with the tempo container but it has the same behaviour when used without anything special around it. I'm not sure what causes this, it might be something in the macro system or the code that's supposed to trigger when the button is released. I'll have to look into that when I redo the macro thing for the new Gremlin version.

**Comment by WhiteMagic** [comment]
Tested again and this works as expected in R13.3
