### ISSUE TITLE
impossible to start from an external program

### ISSUE THREAD

**Issue by mass2110** [WhiteMagic/JoystickGremlin#292]
I try to start Gremlin from a macro key with Razer Synapse, but Gremlin failed to start. I think the problem is Razer Synapse doesn't define the working directory.

**Comment by WhiteMagic** [comment]
I can launch Gremlin via a bat file containing this.
```
cd "path\to\gremlin"
start "" "path\to\gremlin\joystick_gremlin.exe"
exit
```
Maybe you can coax synapse to use this?

**Comment by mass2110** [comment]
Your solution doesn't work for me, same error. But i used this command line.

```
start "" /D "path\to\gremlin" "path\to\gremlin\joystick_gremlin.exe" --profile "path\to\profile\DCS F-16C.xml" --enable --start-minimized
exit
```
