### ISSUE TITLE
Mapping a button on my x56 to two buttons

### ISSUE THREAD

**Issue by JesperAppelberg** [WhiteMagic/JoystickGremlin#293]
I've been trying to map a vjoy button to activate when i press one button on my HOTAS and another one for when i release it, but this does only work on normal buttons, the one I'm trying to map does not work. It is the slider on the X56 and is recognised as a normal button by windows but not by joystick gremlin. This means that i can niether activate a axis nor a button using it in joystick gremlin. I tried following the reddit link below but as i said that only worked for every other button than the one I want to use.
https://www.reddit.com/r/hotas/comments/czkmcz/toggle_switch_release_issue_with_joystick_gremlin/
Anyone that knows how to fix this?
![image](https://user-images.githubusercontent.com/44289844/80755818-c2700100-8b31-11ea-9d5b-ead693b15cae.png)
![image](https://user-images.githubusercontent.com/44289844/80755822-c69c1e80-8b31-11ea-98b9-919f861f1c13.png)

**Comment by WhiteMagic** [comment]
The macro setup and conditions look correct to me, so it should work on that front.

What virtual button setup did you configure in Gremlin? If you didn't configure anything then Gremlin won't do anything. That Windows should see that input as a button while Gremlin sees it as an axis is confusing to me, as both should be based on DirectInput.

**Comment by JesperAppelberg** [comment]
Im equally confused. After a closer inspection I think that joystick gremlin also recognises the button as a button, but I am still unsure of why it refuses to work.

**Comment by JesperAppelberg** [comment]
I am just stupid, sorry for taking your time but it I was mapping the wrong button. Thanks for trying to help though :D
