### ISSUE TITLE
Keyboard rudder controls 

### ISSUE THREAD

**Issue by windin101** [WhiteMagic/JoystickGremlin#302]
Hi 

I am sure I am doing something stupid 

I am trying  to map two keyboard buttons (,.) to the Z Rotation axis to achieve rudder control in some older games.

So far I have been able to assign , to Absolute -1.000 of rotation and  . to Absolute 1.000 rotation of the  Z axis with no issues. Now comes the hard part

When either key is released I would like the Axis to return to center 0.000 but I cant make it work

The set up I have so far is 

![image](https://user-images.githubusercontent.com/67452058/85820679-dbf89680-b7ca-11ea-801b-114d78cd105a.png)

![image](https://user-images.githubusercontent.com/67452058/85820725-fdf21900-b7ca-11ea-84f2-3dd8428cbd09.png)

When any conditions are set the key stop detecting input and I have to delete the macro and start over. I have tried a couple of dozen combination without success. 

Any help is greatly appreciated.

**Comment by ghost** [comment]
Edit: Ignore this, there's new stuff :) See below....

Your conditions state that it should apply the yaw macro when the key is pushed _and_ when it is released. You need a macro to centre yaw when either key is released.

**Comment by WhiteMagic** [comment]
You're running into the issue that the keyboard condition on actions is misbehaving in weird ways, i.e. the condition isn't doing what you think it ought to. The best way around this is to use the "Action Condition" which is actually the one that I intended for people to use for this use case. Once you change the condition things should work, though I had some weird quirks with whether or not the macros would run but in the end it behaved correctly, so I'm not sure what was going on there.

![Annotation 2020-06-30 170746](https://user-images.githubusercontent.com/5612/86094716-3dcf3e00-baf4-11ea-9074-52da22f904a2.jpg)
