### ISSUE TITLE
vJoy buttons missing/gone in Gremlin

### ISSUE THREAD

**Issue by OtakuMage5056** [WhiteMagic/JoystickGremlin#306]
Hi, been using Joystick Gremlin for a couple months now together with vJoy to map all the buttons on my Virpil throttle to a game that has limited HOTAS input availability (but is totally find with obscene numbers of complicated keyboard binds). Got my new grip to go with the throttle today, and was trying to go through the same procedure to map things on it, but the new vJoy device would show 0 buttons in Joystick Gremlin despite being configured to have 31 in vJoy itself. I looked at the previous vJoy device and, where there had been 79 buttons and several axes, were now just axes. I quit without saving the profile, rebooted the PC, and relaunched in the hope that my old setup would be safe. It wasn't, so now I have two vJoy devices that in their own config have 79 and 31 buttons, respectively, but show as 0 buttons and just axes in Gremlin.

Help.

**Comment by WhiteMagic** [comment]
This is the same as this thread https://www.reddit.com/r/hotas/comments/hnryox/vjoy_and_joystickgremlin_help/ correct? I'll just keep it to reddit so we don't duplicate things, but I don't mind really where we try to figure this out.

**Comment by Beardy404** [comment]
I have the same problem. Has anyone found a solution?

**Comment by WhiteMagic** [comment]
At least in the last instance this is regarding the vJoy tab, which is not supposed to show vJoy buttons but only axis, if in the original case that wasn't the problem this should be reopened.

**Comment by VictorValar** [comment]
I have the same problem. How was this solved?

**Comment by WhiteMagic** [comment]
If you have the same "problem", i.e. the vJoy tab is not showing buttons but only axes, then as mentioned above, that's not a problem but supposed to be that way. You are not supposed to assign actions to output vJoy device buttons.
