### ISSUE TITLE
Button release condition not triggering the action

### ISSUE THREAD

**Issue by taipan303** [WhiteMagic/JoystickGremlin#320]
[release_bug.zip](https://github.com/WhiteMagic/JoystickGremlin/files/5106155/release_bug.zip)

I've attached a simple test profile here showing the issue.

The goal of the mapping:
1. When button is pressed and held i want it to send a keyboard key (this works)
2. When the button is then released i want it to send a different keyboard key (this does not send anything)

I've done the mappings as suggested in the documentation, using a condition for each of pressed or released. The pressed action fires but the released action does not. I've tested the condition both as a joystick button condition, and as an action condition with no differences. Also tried putting them in the same container but no difference.

The only way i could get a "release" condition to work was either as a SHIFT function for a different button, or as a TEMPO button with "released" selected on the main action. TEMPO can't be used though because it has a maximum hold time of 2 seconds before release is triggered automatically and i need to hold this button for longer.

Any way to get the "Released" condition to work on the same button?

**Comment by taipan303** [comment]
Another update. The "released" condition works behind a macro, so I put the second action inside a macro and it works. 
Seems to be an issue only with conditions behind remaps.

**Comment by WhiteMagic** [comment]
Yeah, the map to keyboard action cannot be used in this manner. All remap actions are like this because they need to execute both on press and release. This is in contrast with other actions which by default only execute on press. A side effect of this is that when you change the condition you only change which of the two executions happen but not what that execution does. So in your case pressing a key via a condition won't work because all that will happen is the release component being run.

Also, it sounds like you want to send a pulse, i.e. press and release, that is independent of the physical button press. This cannot be accomplished via the map to keyboard action but only the macro action.

**Comment by taipan303** [comment]
Thanks, makes sense. Good the macro works.

You might want to update the documentation page though https://whitemagic.github.io/JoystickGremlin/interface/
The first screenshot in "3.3 Activation Conditions" shows an activation condition on RELEASE for a Remap, which doesn't work.

**Comment by SupremeTechnopriest** [comment]
Hey @WhiteMagic, I am also having a problem getting the release condition to work with a macro action. 

![image](https://user-images.githubusercontent.com/2261598/109731331-e811d080-7b6f-11eb-8682-6237af0c49e7.png)

![image](https://user-images.githubusercontent.com/2261598/109731316-ddefd200-7b6f-11eb-8046-69fbc05d97fa.png)

Pretty straight forward set up.  What is weird is that it was working for a second until I added a similar configuration to another button. Now nothing I do will get it to work. I'm using the Input Viewer and can confirm that the released condition is not firing the macro.

Running version 13.3

**Comment by WhiteMagic** [comment]
If this action is bound to the physical button 37 on that joystick, i.e. the condition is checking the state of the input you're using to trigger the action then this is a known issue with joystick conditions. If you want to check the state of the current input you need to use the "Action" condition.

**Comment by SupremeTechnopriest** [comment]
Cool thanks for the info, I will give that a try!
