### ISSUE TITLE
toggle back and forth between buttons.

### ISSUE THREAD

**Issue by muarqdnph4VPV6dyh** [WhiteMagic/JoystickGremlin#321]
Hi,

can someone please help me, I am struggling to configure a condition. 
I want Joystick Gremlin to do the following:
if I press button 1, button 1 should turn and stay on and button 2 should turn and stay off
if I press button 2, button 2 should turn and stay on and button 1 should turn and stay off
So it should switch back and forth between the two buttons.

Thank you very much

**Comment by WhiteMagic** [comment]
You don't need conditions for this, all that is needed is a macro that performs the two actions you outline. The attached image is the macro assigned to button 1. You'll have to create a second one on button 2 which does the inverse.

![image](https://user-images.githubusercontent.com/5612/90955943-71f82700-e4c5-11ea-860b-753d66def6fb.png)
