### ISSUE TITLE
Old profiles do not work on new PC

### ISSUE THREAD

**Issue by ski-freak** [WhiteMagic/JoystickGremlin#324]
I just moved to a new pc and when I load my old joystick gremlin profiles it seems to load but none of the remappings/macros actually are shown. As you can see in the picture the left side of each button is loaded but not the remap to jvoy on the right.
![Capture](https://user-images.githubusercontent.com/64756991/91581251-d37c2380-e913-11ea-9a06-77410aa9086b.PNG)

**Comment by WhiteMagic** [comment]
This is to be expected, as your profile would have the device guids from your old system and those will have changed with the new windows on your new PC.  You can fix that easily though via the Actions -> Swap Devices dialog as this allows you to move all bindings from the old id to the new one.

**Comment by ski-freak** [comment]
thanks that worked
