### ISSUE TITLE
Press Joystick Button and Hold to send multiple Key Presses

### ISSUE THREAD

**Issue by able724** [WhiteMagic/JoystickGremlin#325]
The difficulty I am having is this.
example:
shift + s increases a value in game

I would like to be able to hold down the button and have the joystick rapidly send shift + s multiple times.  The problem I'm having is that it is not sending the press shift, press s, release s, release shift but rather the order gets mixed up and so the game doesn't interpret it correctly.

Is this a limitation of joystick gremlin or am I not putting it in right by recording it as a 'map to keyboard'?  If I record it as a Macro, it seems to work ok, but the timing is slow enough that it isn't usable for what I need.  (trying to control Flaps in a flight sim).

Thank you for your help.

**Comment by WhiteMagic** [comment]
You can't use the remap to keyboard action to have something repeat. All that action does behind the scenes is create two macros, one pressing the keys specified and another one releasing them when the physical key is pressed. The ordering of the keys may be mixed which is causing issues in certain cases.

The macro is what you should want to use as that will send the keys in exactly the order you specify and if you use the hold repeat mode it will repeat the macro as long as the physical input is held down. You may have to play with the delays between individual macro entries and on the hold repeat action to get the tempo you're after.

**Comment by able724** [comment]
Thanks.  That explains some of the issues I've had with modified key presses like Shift + L triggering the L action on release.
