### ISSUE TITLE
Linux equivalent? Or does this work on linux?

### ISSUE THREAD

**Issue by ski-freak** [WhiteMagic/JoystickGremlin#326]
I have been using this for some months now with my 12 year old controller, and I am now using linux. However as far as I can tell this uses the windows device manager stuff to take inputs and forward them to Vjoy, which I would guess doesn't work on linux and I don't see a way to install it anyway.

So is there a way to make this work on linux or an alternative for linux?

**Comment by WhiteMagic** [comment]
No Gremlin won't be usable on Linux. While it's written in Python and uses Qt for the UI the actual aspects that make it do something are Windows specific, i.e. reading device input, feeding vJoy devices, and emitting key strokes. I'm not aware of similar tools for Linux, however, I have in the past used https://github.com/tuomasjjrasanen/python-uinput to control virtual joysticks on Linux systems.

**Comment by ski-freak** [comment]
Yeah sadly that is about what I expected.

**Comment by Kabouik** [comment]
Hijiacking this issue to check whether it has been tested with Wine/Proton. With MSFS2020, DCS and some IL-2 games now working okayish with Proton, using Joystick Gremlin in the same wineprefix could perhaps work? Of course this would not solve the issue for native Linux simulators, but a fair proportion of simulators are not native.

I'm using a Windows cloud computing service right now but am not far to switching back to local Linux + Wine only. Unfortunately I'm fully dependent on Joystick Gremlin for my custom made throttle, as there are buttons that won't work as intended at all without Joystick Gremlin's magic.

**Comment by WhiteMagic** [comment]
No idea, the biggest question mark is probably whether or not vJoy will work in such a setup or not.
