### ISSUE TITLE
Radio Buttons

### ISSUE THREAD

**Issue by DCrean** [WhiteMagic/JoystickGremlin#332]
I'm terribly sorry if there's already a request for this, but I'm trying to get some radio button functionality working.

If any button in a group is activated, it stays on and releases any other buttons that were pressed. 
If the button that is activated is pressed, it releases so that no buttons in the group are pressed.

Basically have a group of virtual buttons that will only have (at most) one pressed button at any time, with the option to allow a second press on the active button to turn it off.

I am attempting to write a plugin to do exactly this, but I am not familiar with Python or JG's API. 
If I have any success setting this up, I will update this issue.

**Comment by BenBlake79** [comment]
This should be pretty simple using a vjoy device. Just make a macro for every button in the group. Each macro has a release only for the other buttons and a press for itself. Give it the action condition "button released" for the corresponding vjoy button. Now make another macro for every button which only releases this button and set the action condition to "button pressed" for the corresponding vjoy button.
When I'm home I could tell you the exact names for the action conditions.

**Comment by BenBlake79** [comment]
It is called vJoy Condition and you have to choose the corresponding vJoy Button (Pressed and Released)

**Comment by DCrean** [comment]
I did give that a try at first, however I was having some trouble getting the macros to fire with the right timing. I also didn't feel like making 280+ macros (5 modes across 7 [4-way] hats) Today I did manage to get a plugin working that accepts an input, 2 modifier buttons, and 4 (vjoy) outputs. It toggles the pressed button (based on the single physical input and 2 physical modifiers) and sets the other 3 to off. Here's the plugin code, but it _is_ the first thing I've ever written in Python, so it's not great.
````
import gremlin
from gremlin.user_plugin import *

#UI Input Thingies
mode = ModeVariable(
        "Mode",
        "The mode to use for this instance"
)
joy_button = PhysicalInputVariable(
        "Main Button",
        "Main physical input button",
        [gremlin.common.InputType.JoystickButton]
)
joy_mod_1 = PhysicalInputVariable(
        "Modifier 1",
        "Modifier 1 physical button",
        [gremlin.common.InputType.JoystickButton]
)
joy_mod_2 = PhysicalInputVariable(
        "Modifier 2",
        "Modifier 2 physical button",
        [gremlin.common.InputType.JoystickButton]
)
vjoy_1 = VirtualInputVariable(
        "Default Virtual Button",
        "Virtual button activated with no modifiers",
        [gremlin.common.InputType.JoystickButton]
)
vjoy_2 = VirtualInputVariable(
        "Mod 1 Virtual Button",
        "Virtual button activated modifier 1",
        [gremlin.common.InputType.JoystickButton]
)
vjoy_3 = VirtualInputVariable(
        "Mod 2 Virtual Button",
        "Virtual button activated modifier 2",
        [gremlin.common.InputType.JoystickButton]
)
vjoy_4 = VirtualInputVariable(
        "Mod 1 & 2 Virtual Button",
        "Virtual button activated with both modifiers",
        [gremlin.common.InputType.JoystickButton]
)
#global things
decorator_1 = joy_button.create_decorator(mode.value)
v_out1_state = False
v_out2_state = False
v_out3_state = False
v_out4_state = False

#Figures out what state the virtual buttons are supposed to be in
def resolve_state(joy, vjoy):
    global joy_mod_1, joy_mod_2, v_out1_state, v_out2_state, v_out3_state, v_out4_state
    mod_1 = joy[joy_mod_1.value["device_id"]].button(joy_mod_1.value["input_id"]).is_pressed
    mod_2 = joy[joy_mod_2.value["device_id"]].button(joy_mod_2.value["input_id"]).is_pressed
    v_out1_current = vjoy[vjoy_1.value["device_id"]].button(vjoy_1.value["input_id"]).is_pressed
    v_out2_current = vjoy[vjoy_2.value["device_id"]].button(vjoy_2.value["input_id"]).is_pressed
    v_out3_current = vjoy[vjoy_3.value["device_id"]].button(vjoy_3.value["input_id"]).is_pressed
    v_out4_current = vjoy[vjoy_4.value["device_id"]].button(vjoy_4.value["input_id"]).is_pressed
    v_out1_state = False
    v_out2_state = False
    v_out3_state = False
    v_out4_state = False
    if not mod_1 and not mod_2:
        v_out1_state = not v_out1_current
    elif mod_1 and not mod_2:
        v_out2_state = not v_out2_current
    elif not mod_1 and mod_2:
        v_out3_state = not v_out3_current
    elif mod_1 and mod_2:
        v_out4_state = not v_out4_current

#Set the button to their intended states
def change_state(vjoy):
    global v_out1_state, v_out2_state, v_out3_state, v_out4_state
    vjoy[vjoy_1.value["device_id"]].button(vjoy_1.value["input_id"]).is_pressed = v_out1_state
    vjoy[vjoy_2.value["device_id"]].button(vjoy_2.value["input_id"]).is_pressed = v_out2_state
    vjoy[vjoy_3.value["device_id"]].button(vjoy_3.value["input_id"]).is_pressed = v_out3_state
    vjoy[vjoy_4.value["device_id"]].button(vjoy_4.value["input_id"]).is_pressed = v_out4_state

@decorator_1.button(joy_button.input_id)
def joy_event(event, joy, vjoy):
    global joy_button, joy_mod_1, joy_mod_2
    try:
        if event.is_pressed and joy_button is not None and joy_mod_1 is not None and joy_mod_2 is not None:
            joy_init = gremlin.input_devices.JoystickPlugin.joystick
            vjoy_init = gremlin.input_devices.VJoyPlugin.vjoy
            resolve_state(joy_init, vjoy_init)
            change_state(vjoy_init)
    except:
        gremlin.util.log('CAUGHT error in radio toggle plugin')
````

**Comment by BenBlake79** [comment]
280 Macros?
You know that you've got mode inheritance?
And you can copy Macros from one Button to another in an editor.
I made your functionality for 6 Buttons (12 macros) in about 3 or 4 minutes:


                `<button description="" id="1">
                    <container type="basic">
                        <action-set>
                            <macro>
                                <properties/>
                                <actions>
                                    <vjoy input-id="1" input-type="button" value="True" vjoy-id="1"/>
                                    <vjoy input-id="2" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="3" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="4" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="5" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="6" input-type="button" value="False" vjoy-id="1"/>
                                </actions>
                                <activation-condition rule="all">
                                    <condition comparison="released" condition-type="vjoy" id="1" input="button" vjoy-id="1"/>
                                </activation-condition>
                            </macro>
                            <macro>
                                <properties/>
                                <actions>
                                    <vjoy input-id="1" input-type="button" value="False" vjoy-id="1"/>
                                </actions>
                                <activation-condition rule="all">
                                    <condition comparison="pressed" condition-type="vjoy" id="1" input="button" vjoy-id="1"/>
                                </activation-condition>
                            </macro>
                        </action-set>
                    </container>
                </button>
                <button description="" id="2">
                    <container type="basic">
                        <action-set>
                            <macro>
                                <properties/>
                                <actions>
                                    <vjoy input-id="1" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="2" input-type="button" value="True" vjoy-id="1"/>
                                    <vjoy input-id="3" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="4" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="5" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="6" input-type="button" value="False" vjoy-id="1"/>
                                </actions>
                                <activation-condition rule="all">
                                    <condition comparison="released" condition-type="vjoy" id="2" input="button" vjoy-id="1"/>
                                </activation-condition>
                            </macro>
                            <macro>
                                <properties/>
                                <actions>
                                    <vjoy input-id="2" input-type="button" value="False" vjoy-id="1"/>
                                </actions>
                                <activation-condition rule="all">
                                    <condition comparison="pressed" condition-type="vjoy" id="2" input="button" vjoy-id="1"/>
                                </activation-condition>
                            </macro>
                        </action-set>
                    </container>
                </button>
                <button description="" id="3">
                    <container type="basic">
                        <action-set>
                            <macro>
                                <properties/>
                                <actions>
                                    <vjoy input-id="1" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="2" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="3" input-type="button" value="True" vjoy-id="1"/>
                                    <vjoy input-id="4" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="5" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="6" input-type="button" value="False" vjoy-id="1"/>
                                </actions>
                                <activation-condition rule="all">
                                    <condition comparison="released" condition-type="vjoy" id="3" input="button" vjoy-id="1"/>
                                </activation-condition>
                            </macro>
                            <macro>
                                <properties/>
                                <actions>
                                    <vjoy input-id="3" input-type="button" value="False" vjoy-id="1"/>
                                </actions>
                                <activation-condition rule="all">
                                    <condition comparison="pressed" condition-type="vjoy" id="3" input="button" vjoy-id="1"/>
                                </activation-condition>
                            </macro>
                        </action-set>
                    </container>
                </button>
                <button description="" id="4">
                    <container type="basic">
                        <action-set>
                            <macro>
                                <properties/>
                                <actions>
                                    <vjoy input-id="1" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="2" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="3" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="4" input-type="button" value="True" vjoy-id="1"/>
                                    <vjoy input-id="5" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="6" input-type="button" value="False" vjoy-id="1"/>
                                </actions>
                                <activation-condition rule="all">
                                    <condition comparison="released" condition-type="vjoy" id="4" input="button" vjoy-id="1"/>
                                </activation-condition>
                            </macro>
                            <macro>
                                <properties/>
                                <actions>
                                    <vjoy input-id="4" input-type="button" value="False" vjoy-id="1"/>
                                </actions>
                                <activation-condition rule="all">
                                    <condition comparison="pressed" condition-type="vjoy" id="4" input="button" vjoy-id="1"/>
                                </activation-condition>
                            </macro>
                        </action-set>
                    </container>
                </button>
                <button description="" id="5">
                    <container type="basic">
                        <action-set>
                            <macro>
                                <properties/>
                                <actions>
                                    <vjoy input-id="1" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="2" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="3" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="4" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="5" input-type="button" value="True" vjoy-id="1"/>
                                    <vjoy input-id="6" input-type="button" value="False" vjoy-id="1"/>
                                </actions>
                                <activation-condition rule="all">
                                    <condition comparison="released" condition-type="vjoy" id="5" input="button" vjoy-id="1"/>
                                </activation-condition>
                            </macro>
                            <macro>
                                <properties/>
                                <actions>
                                    <vjoy input-id="5" input-type="button" value="False" vjoy-id="1"/>
                                </actions>
                                <activation-condition rule="all">
                                    <condition comparison="pressed" condition-type="vjoy" id="5" input="button" vjoy-id="1"/>
                                </activation-condition>
                            </macro>
                        </action-set>
                    </container>
                </button>
                <button description="" id="6">
                    <container type="basic">
                        <action-set>
                            <macro>
                                <properties/>
                                <actions>
                                    <vjoy input-id="1" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="2" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="3" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="4" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="5" input-type="button" value="False" vjoy-id="1"/>
                                    <vjoy input-id="6" input-type="button" value="True" vjoy-id="1"/>
                                </actions>
                                <activation-condition rule="all">
                                    <condition comparison="released" condition-type="vjoy" id="6" input="button" vjoy-id="1"/>
                                </activation-condition>
                            </macro>
                            <macro>
                                <properties/>
                                <actions>
                                    <vjoy input-id="6" input-type="button" value="False" vjoy-id="1"/>
                                </actions>
                                <activation-condition rule="all">
                                    <condition comparison="pressed" condition-type="vjoy" id="6" input="button" vjoy-id="1"/>
                                </activation-condition>
                            </macro>
                        </action-set>
                    </container>
                </button>`

But I am an absolute greenhorn when it comes to plugins and Python so maybe your solution is better? I do not know. But if it works, maybe WhiteMagic will publish it together with the other User Plugins?

But from what I understood You need this functionality across all Modes and Shift Keys? Then you just would have to use mode inheritance and don't care for the Shift Buttons as these are action/container conditions only and if you have no condition the function will be triggered independently from a Shift button beeing pressed or not... 
And what do you mean by "timing troubles"?

**Comment by WhiteMagic** [comment]
It would be possible to implement something like this via modes but it might be a bit finicky depending on the sequence in which modes are being switched around. While manually editing the XML file works it's really not ideal as any change in logic might require redoing everything, so from that point of view a user plugin is much better.
