### ISSUE TITLE
Uncaught Exception Traceback

### ISSUE THREAD

**Issue by Jancarius** [WhiteMagic/JoystickGremlin#333]
When attempting to launch Joystick Gremlin, I encounter this error.  I'm new to joystick setups, but it was working previously when I had a Saitek X52 Pro plugged in.  I am today attempting to configure a new Virpil Const-Alpha and a Mongoose.
![image](https://user-images.githubusercontent.com/74219074/98613044-1f0b6000-22bb-11eb-97ea-ededeb99205f.png)

**Comment by WhiteMagic** [comment]
This is likely the same problem as #319. Apparently modifying the device name in the Windows registry can temporarily solve the issue until I can fix this aspect of Gremlin.
