### ISSUE TITLE
Allow HidGuardian settings to be tied to a profile

### ISSUE THREAD

**Issue by jgentil** [WhiteMagic/JoystickGremlin#338]
Right now Joystick Gremlin can hide or unhide joysticks with HidGuardian, but only globally in settings.

It would be really nice to have a per-profile configuration for this.  That way when it auto-detects my profile based on process, it can automatically hide or show certain inputs.

**Comment by WhiteMagic** [comment]
While the idea is good it sadly is technically impossible to implement this. HidGuardian requires unplugging and plugging back in of devices for changes made to device hiding to take effect. As such it is impossible to automate hiding and showing of devices by tying it to a profile.
