### ISSUE TITLE
Feature Request: Joystick Button to Mouse Wheel Scroll Emulation 

### ISSUE THREAD

**Issue by jcdied4me** [WhiteMagic/JoystickGremlin#340]
I have been using the Virpil Alpha joysticks in Star Citizen. The joysticks have a scroll wheel each. This sounds great on paper but they are not helpful. They do not emulate the actual mouse wheel but merely repeats button presses. Scrolling up is mapped to one button press and scroll down is mapped to another. 

I would love a feature that would allow JG to use button presses to emulate the scroll wheel.

I found this amazing mouse emulator that allows mouse actions through numpad key presses. It works really well for keys to scroll wheel emulation. I tried to run the emulator then JG, and then remapped the scroll wheel buttons to the keys needed for the mouse emulator, but it did not work. I assume that JG and MouseMU does not play well together.
http://rhdesigns.browseto.org/mouseemulator.html

I hope that this makes sense. And if there is a feature like this already please let me know. I implemented all of the mouse mapping options currently in JG to no avail. Any help would be greatly appreciated.

Thank you!
Jeff

**Comment by WhiteMagic** [comment]
This is already possible via the macro action where you can emulate mouse motion and button presses, including mouse wheel motions.
