### ISSUE TITLE
support for njz3's fork

### ISSUE THREAD

**Issue by voshond** [WhiteMagic/JoystickGremlin#345]
hi, i was using the newer build for vjoy from https://github.com/njz3/vJoy fork.
However when using this vJoy version, Joystick Gremlin seems to be unable to remap any input the the virtual devices.

any chance support might be added?

**Comment by WhiteMagic** [comment]
That entirely depends on what this entails. If this fork means other currently supported vJoy versions no longer work then there has to be a really good reason for me to consider breaking working vJoy setups.

**Comment by voshond** [comment]
Hi @WhiteMagic ,

If you check the original project: https://github.com/shauleiz/vJoy pointed to for an updated version: https://github.com/jshafer817/vJoy which since mid 2020 now points to https://github.com/njz3/vJoy, which is the currently actively maintained version and added quite a few features.

**Comment by gponick** [comment]
Fwiw, people have reported success in discord by:

https://discord.com/channels/438688364359581707/528501166385135636/791778441208266752

(on this server: https://discord.gg/szqaJE7)

```fixed: replaced the vJoyInterface.dll with the non amd64 version from here: https://github.com/njz3/vJoy/releases/download/v2.2.1.1/vJoy-2.2.1.1-SDK.zip```

**Comment by voshond** [comment]
> Fwiw, people have reported success in discord by:
> 
> https://discord.com/channels/438688364359581707/528501166385135636/791778441208266752
> 
> `fixed: replaced the vJoyInterface.dll with the non amd64 version from here: https://github.com/njz3/vJoy/releases/download/v2.2.1.1/vJoy-2.2.1.1-SDK.zip`

unfortunately unable to open the link. I also don't not which files exactly, as i am not familiar with JoystickGremlins file structure. Could you elaborate?

**Comment by gponick** [comment]
> unfortunately unable to open the link. I also don't not which files exactly, as i am not familiar with JoystickGremlins file structure. Could you elaborate?

Sure. Here's what I did. To be clear I'm using vJoy `v2.2.1.1` and Joystick Gremlin `v13.3`. 

1. Open your Joystick Gremlin folder and rename `vJoyInterface.dll` to `vJoyInterface.dll.old`. 
2. Grab the vJoy SDK for the vJoy version in use (in my case I was using vJoy `v2.2.1.1`, so I used the vJoy SDK from here: https://github.com/njz3/vJoy/releases/download/v2.2.1.1/vJoy-2.2.1.1-SDK.zip). Inside you'll find a bunch of files, take the `vJoyInterface.dll` from `SDK/lib/` inside the zip archive and put it directly into your Joystick Gremlin folder. 
3. Axis mapping now works.

FWIW, I'm not the author of Joystick Gremlin or anything else. Just saw a fix posted and it worked for me as well, so I figured I'd post.

**Comment by vdubus** [comment]
Got the same issue.
I installed the version from **njz3/vJoy** as pointed out by  **jshafer817/vJoy** repo, but Joystick Gremlin didn't seem to be able to send the input to the vJoy device.

I have tested the above answer, and it does seem to fix the issue.

**Comment by neilser** [comment]
> Got the same issue.
> I installed the version from **njz3/vJoy** as pointed out by **jshafer817/vJoy** repo, but Joystick Gremlin didn't seem to be able to send the input to the vJoy device.
> 
> I have tested the above answer, and it does seem to fix the issue.

I read the README info for both repos yesterday and didn't see any suggestion that the interface had changed, but I guess it must have done?

**Comment by WhiteMagic** [comment]
As the njz3 variant has repeatedly been the source of issues and the version by jshafer works without problems there is little point in attempting to include support.

**Comment by Kuiriel** [comment]
The recommended version is worth stickying maybe. I just spent the last couple of hours trying to work out why Joystick Gremlin wouldn't work, and it's because I was using the wrong version of vjoy. With three (or more) versions out there it's worth putting this somewhere even un-clever folk like me can see it, when we feel like we're so clever looking up the latest branch.

*headdesk*

Ow

**Comment by WhiteMagic** [comment]
The correct version is linked in the documentation pages of Gremlin, though the readme on the repo only points at the original vJoy page, I'll update that. If you found an "outdated" link somewhere else let me know so I can update that.

**Comment by Kuiriel** [comment]
You do link to the correct version, it's just that people trying to be smart or randomly remembering they need vjoy may go to https://sourceforge.net/projects/vjoystick/ which links to the njz3 version, or they may scroll down on jshafter817's page and see him linking to njz3 as well and thus we don't realize that new version = not compatible. For the sake of saving yourself the headache of people like me raising the same issue repeatedly, a warning may be helpful XD

Thank you for the awesome software
