### ISSUE TITLE
More than 8 axis vjoy device

### ISSUE THREAD

**Issue by BD5M** [WhiteMagic/JoystickGremlin#349]
Having a problem using more than 8 axis. looking at the debug it shows that the device has 16 axis but the ignores them all after the first 8 is there a way to make it show the all of them instead of it defaulting to the 8?

**Comment by WhiteMagic** [comment]
If you have a vJoy device with more than 8 axes, something is horribly wrong. A DirectInput device cannot have more than 8 axes. Some versions of vJoy somehow manage to give the impression of there being more than 8 axes, but DirectX does not support that in any way.

**Comment by BD5M** [comment]
/ahh right. thats a shame. i was using njz3 (https://github.com/njz3/vJoy/) vjoy and the feeder demo shows 16 and your program says it has 16 but then forces it to 8. so i thought it may just of needed to be able to show them and configure them. was hoping it could get away with not having to use 2 vjoy devices. as its just the axes im lacking ( i need like 10 lol) but ahwell. Thank you for the time though love your program.

**Comment by BD5M** [comment]
yeah from what I can see the problem is the extra axes are HID usage addons. 0x38,0xC4, etc. (not sure of the links but the main place I fount was in nzj3's Wrapper.cs), I don't know what and how the limitation works. is the limit for DirectInput  the program/game/driver or all of the above?

**Comment by WhiteMagic** [comment]
The DirectInput API has hardcoded support for 8 axes only and anything that tries to put more than that into a single device likely will not work with any single game or application which uses that API. So you will have to create two vJoy devices to get the number of axes you require.

The HID protocol itself might be happy with an arbitrary number of axes etc. but DirectInput / DirectX itself can't deal with that it uses the following state structure https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ee416628(v=vs.85)

**Comment by BD5M** [comment]
Sorry i had thought i had closed this a while ago.
