### ISSUE TITLE
FloatVariable does not allow negative values

### ISSUE THREAD

**Issue by edwardwbarber** [WhiteMagic/JoystickGremlin#365]
The Joystick Gremlin GUI does not seem to allow negative values to be entered for FloatVariable. Nor are they allowed for as default values:

```python
testfloat = FloatVariable(
    "Test float",
    "Test float",
    -0.1,
    -1.0,
    1.0
)
```

Output of above defaults to `0.0`. Expected `-0.1`. Attempts to enter `-0.1` manually into GUI widget are reset to `0.0`.

Looks like `QtWidgets.QDoubleSpinBox.Maximum` and `QtWidgets.QDoubleSpinBox.Minimum` aren't assigned to the limits given in `FloatVariable`. Seems like this could be fixed by inserting the following after line 345 in `gremlin/user_plugin.py` (haven't been able to create a 32-bit python 3.4 env to build JoystickGremlin or I would test it myself...):

```python
value_widget.setMaximum(float(self.max_value))
value_widget.setMinimum(float(self.min_value))
```

This might also avoid some of the confusion raised in #359. As it is the GUI lets a user enter up to 99.99 as a float, only to be ignored under the hood :)

Cheers, 
-Edward

**Comment by WhiteMagic** [comment]
Fixed with 37ba776.
