### ISSUE TITLE
Profile with mistake

### ISSUE THREAD

**Issue by simracer1234** [WhiteMagic/JoystickGremlin#371]
Hi 

I made a profile, macros didnt execute, I cant see calues at input viewer or vJoy device properties. 
What is/are my mistake?
Profile link
[](url) https://drive.google.com/file/d/1HuKWDyXjZsKmNGZfCak-2e0Tflg1vfq/view?usp=sharing
Profile have 3 macros

Gear down, cointainer condition pressed button1 released button 2. I want this macro will be execute pushing button 1.

Gear Up, container condition pressed button 2 released button 1. I want this macro will be execute pushing button 2.

Launch control, container condition Simpedal Axis2(clutch) between -0.050 & -0.059 (because first macro value is -0.060 vjoy clutch) button 12 pressed. I want macro will execute when release clutch pedal. 
Use mode: push clutch more than -0.049 press button 12, wait until green lights then release clutch. 

Thanks for reading

**Comment by simracer1234** [comment]
[Completo.zip](https://github.com/WhiteMagic/JoystickGremlin/files/6918576/Completo.zip)

**Comment by WhiteMagic** [comment]
The macro on labeled "Clutch" won't ever trigger because the condition expects button 12 to be pressed and released at the same time which is impossible. That input also seems to have a mix of action and container based conditions which should not be possible.

The other two bindings look sensible to me, so I guess I will need to know more about what is happening or not and whether or not simpler setup work to be able to help further.

**Comment by simracer1234** [comment]
Thanks for fast reply
I joined to discord HOTAS/HOSAS/SIMPIT to try talk with you but, impossible agree rules. 
Read Rules, Check box push agree button, always show same message, "requeriments for this server changed, close this windows a try again" loop mode.

[Completo.zip](https://github.com/WhiteMagic/JoystickGremlin/files/6924609/Completo.zip)
My profile completo clutch conditions are Axis2 between -0.050 & -0.059 and Button12 pressed
screenshot https://ibb.co/fYB7Yd1
I fixed using this : 
[updown2.zip](https://github.com/WhiteMagic/JoystickGremlin/files/6925117/updown2.zip)

Button 6 to start point clutch
https://ibb.co/Hds0knf
button 12 pushed to leave progresive clutch
https://ibb.co/Vt8n1Xp

I have other problems now
-vjoy1 is needed for another app. Is Joystick gremling locking all vjoys 1 & 2? Because other app isnt working now, if is yes. Could only lock vjoy2?

-I think macros of button 1 & 2 are wrong because game dont recognize vjoys axis values from joystickgremlin, but other macros with axis values yes. Im turning crazy after 16h 😂 
I attach video.
[gremlin.zip](https://github.com/WhiteMagic/JoystickGremlin/files/6925200/gremlin.zip)
