### ISSUE TITLE
I would appreciate any commentary on this, I don't know whats going on

### ISSUE THREAD

**Issue by ozturkkl** [WhiteMagic/JoystickGremlin#372]
Hi,

I have a question regarding my setup.

My Xbox One controller left stick was not registering in the center when released, It bothered me so much that I opened it up, went through all the hassle, did some soldering, and replaced the sensor inside. Turns out the new sensor has the same issue. Then I searched for software solutions (because Windows 10 calibration tool doesn't work for any game it's so stupid). I found JoystickGremlin. 

This is an amazing software and I really like the calibration and monitoring tools so I've created the perfect vJoy controller with pinpoint accuracy. The problem is, most games need an Xbox controller input supported device or whatever to work. Steam for example enables you to use generic controllers by assigning the buttons inside their layout editing screen. But then if I try launching games from other launchers that are not as good as Steam (Don't want to name any names ..Xbox ahem), games are unable to detect the vjoy device since it's not an xinput device. On top of that since installing vjoy changes xbox controller driver, now the xbox controller will stop working as well.

**Original xbox one controller driver that I can restore by updating it in the device manager:** (Works in games but vjoy device is not working even though Gremlin shows it as working)
![image](https://user-images.githubusercontent.com/51798197/128427728-669fc94a-2a26-4298-ba24-2ce516b4fb35.png)
![image](https://user-images.githubusercontent.com/51798197/128427747-73724f65-2478-4d10-92c7-69d7e11b6f92.png)

**After vjoy changes it** (Z axis and Z rotation is separate vjoy device works as intended but games won't see the device as xinput anymore)
![image](https://user-images.githubusercontent.com/51798197/128428223-6ff4fb84-4e8d-4df7-accb-f066bb9ee020.png)
![image](https://user-images.githubusercontent.com/51798197/128428183-4b18f2bc-5d3f-46bd-b920-9e70eccb7cfa.png)

Sorry for the long explanation, I don't know how else to describe the issue.

Gremlin seems like it is able to work with both versions of the driver and the Gremlin Input Viewer always shows Vjoy device outputting the actions correctly.

So the final question is, how is it possible that when Gremlin shows that vjoy device is working in the Input Viewer, when I go to windows game controllers or in game, the vjoy device is frozen solid.

![image](https://user-images.githubusercontent.com/51798197/128430440-e41f1c29-cee7-4fb7-88b4-0631d088de76.png)
![image](https://user-images.githubusercontent.com/51798197/128430464-1a83defe-caec-4b31-b53c-9a6925ab9cf6.png)

**Comment by ozturkkl** [comment]
Again very sorry for the long question, I really appreciate it if you read it. You are the best <3

**Comment by WhiteMagic** [comment]
It sounds like there are multiple things going on here.

For starters, if a game only reacts to XInput (the protocol Microsoft introduced to get rid of DirectInput) then vJoy will likely not be seen as it emulates a DirectInput device and as such can only be read by programs/games that use that API.

I'm not sure what causes Windows to trigger some sort of driver update that changes the xbox controller updated, that's likely some weird crazy Windows thing. The reason Gremlin likely is able to handle either device/driver is that most XInput devices also expose themselves via DirectInput, which is the API Gremlin uses.

The last issue is likely a fun "feature" that Microsoft added to their controllers. The Xbox controller can be read via DirectInput, however, unlike every other device, only the program that has focus can read the controller using DirectInput, if it was read via XInput that would not be the case. This is something I will eventually fix by adding XInput fallback to the library I use for reading device information.

**Comment by ozturkkl** [comment]
Wow that explains a lot, I ended up using x360ce to create a virtual box 360 controller and then redirect all the output to that to be able to use it in every game. 

What I discovered is, basically if you want your input device to be compatible in every game and in every launcher on windows, you have to use some sort of xinput output.

Amazing software you created here, thank you for the quick response as well, god bless :D
