### ISSUE TITLE
Unable to Map Button to POV hat

### ISSUE THREAD

**Issue by Bacon8tor** [WhiteMagic/JoystickGremlin#374]
I have looked everywhere, dont see a way to map a button to vJoy POV Hat. I see you can do POV hat to button, and hat to hat. Am I missing something here?

**Comment by WhiteMagic** [comment]
There is no way to map a single button to a PoV hat as that mapping is ill-defined. What you can do, however, is to map a single button to a PoV hat direction via the Macro action. The macro would need to set a vJoy PoV hat direction when being pressed, and set the PoV hat to neutral again when the physical button is released.
