### ISSUE TITLE
Reset relative axis?

### ISSUE THREAD

**Issue by mkaito** [WhiteMagic/JoystickGremlin#377]
Hi!

I'm using two relative axis remaps to move a camera around. I'd love a button mapped to reset these two axis back to center. What would be the best way to do this?

**Comment by WhiteMagic** [comment]
A macro action that sends absolute vJoy axis values of 0 to each axis should do the trick for that.

**Comment by mkaito** [comment]
That did the trick indeed.

There's also some odd behaviour regarding relative axis with a response curve. They "go back" when you release the axis. Is this a known issue, should I make a new issue for that, or am I doing something wrong?

**Comment by WhiteMagic** [comment]
It depends on what your response curve looks like, if it sends a non-zero value at rest then it is expected that the value will change, as Gremlin won't see a zero anymore but whatever value the response curve provides.
