### ISSUE TITLE
Feature Request - change order of keyboard combinations to more natural

### ISSUE THREAD

**Issue by Ras-Tafari** [WhiteMagic/JoystickGremlin#379]
Hello,

I wish to make a feature request, it isn't something really necessary more quality of life thing. When using keyboard combinations with "map to keyboard" action I would like the "_releases_" of buttons to be done in **reversed order** of "_presses_". 

Example:

![image](https://user-images.githubusercontent.com/4569855/134523758-367ac80f-eeb5-4c3a-bd58-19669d97a581.png)
 
would result in:

![image](https://user-images.githubusercontent.com/4569855/134523938-5709d5cd-6684-4545-8039-565e3755a195.png)

instead of:

![image](https://user-images.githubusercontent.com/4569855/134523881-1a080bb0-0cdd-4567-993c-d91bd5356ef9.png)

Why? Proposed order is more natural and it mimics the real order of using keyboard combinations properly. In most cases it usually isn't producing any errors but some sims (for example Il2 Sturmovik) do unpredictable things example "_Left Control + F_" being recognized as "_Left Control + F, F_".

Currently we can obtain desired output using macros, which is great but when you have to map tens simple combinations as macros it become laborious.

Whether you gonna implement it or not I still would like to say thanks for your work, I've made recent transition from T.A.R.G.E.T. script + Logitech soft combo to JG and I'm truly happy with it.

**Comment by WhiteMagic** [comment]
See 626787b58f0e9bb0a8d44002857d7eafc894f0e2
