### ISSUE TITLE
Bug: Button # preview in left pane doesn't update until profile saved & reloaded

### ISSUE THREAD

**Issue by Jahfry** [WhiteMagic/JoystickGremlin#382]
Minor issue noticed tonight. 

When changing the button assignment for a remap, the number of the assigned button doesn't change in the left pane until the profile has been saved and reloaded. 

* Screenshot below shows Button1 on a gamepad that was 1:1 mapped to Button1 on vJoy1 (other buttons have been changed/added remaps but this one so far had not been changed after doing 1:1)
* After doing that I changed the button remap from Button1 to Button2. 
* The left pane still shows Button1 assigned. 
* Stopping/Starting profile didn't update left pane
* Saving profile, Loading it back in, *does* update left pane

![Screenshot 2021-11-21 212828](https://user-images.githubusercontent.com/16520816/142796898-f95d45df-84dc-4866-a365-6afcda6537d9.png)

**Comment by WhiteMagic** [comment]
Yeah, that but has been introduced at some point and it's a bit inconsistent in triggering itself. Though, this is unlikely to get fixed as the entire code responsible for the UI is being redone.
