### ISSUE TITLE
Feature Request: User Reset/Reassignment of Device GUID and Product ID

### ISSUE THREAD

**Issue by TheGoodIdeaFairy** [WhiteMagic/JoystickGremlin#409]
The user should be able to change the identifiers associated with a given Action-Set through the UI.  Currently if either the GUID or Product ID (this is how Virpil names it, unsure if this is official; it's a 4 character hex field in the 'Profile' tab of the VPC Config tool)

The current workaround when the GUID changes (for instance, upon a firmware update) is to manually edit the Profile XML and find/replace the offending GUID.

Thank you.

**Comment by WhiteMagic** [comment]
This is what the Actions -> Swap Devices functionality is there for. There is a bug in this where descriptions are not correctly copied across.

**Comment by TheGoodIdeaFairy** [comment]
How the heck did I miss that.  I guess I just assumed it would be in Tools or Options and didn't check elsewhere.  Thanks.

**Comment by WhiteMagic** [comment]
The name doesn't exactly call out that it does this, mainly because the reason it was added was for a slightly different use case, which has the same needs.
