### ISSUE TITLE
Action Conditional Dropdowns Reset

### ISSUE THREAD

**Issue by TheGoodIdeaFairy** [WhiteMagic/JoystickGremlin#414]
When JG is deactivated some Condition dropdown options will reset to defaults, especially if they currently shown in the display window.

It seems to be isolated to the vJoy Conditions, but all dropdowns of this type will consistently reset to the default value.

**Comment by WhiteMagic** [comment]
This is the same issue mentioned in #361 and #407.

**Comment by TheGoodIdeaFairy** [comment]
Ahh, missed #361 and didn't check the pull requests so I missed #407 as well.  Sorry about that.
