### ISSUE TITLE
Mode Switch Causes Release Action to be Ignored

### ISSUE THREAD

**Issue by TheGoodIdeaFairy** [WhiteMagic/JoystickGremlin#417]
If a Mode Switch is set as the Press action, the Release action of that button is not executed.

**Comment by WhiteMagic** [comment]
That is how the logic of modes works. If you switch from `A` to `B` upon pressing the button the only release action that would be executed is the one in `B` but not `A`, as that's no longer the active mode. Certain actions account for this, for example, the remap action which uses trickery to trigger the release action. However, only remap-like actions do have a defined press and release functionality and thus only they have this treatment.

**Comment by TheGoodIdeaFairy** [comment]
Got it.  That's a little unintuitive, but thanks for helping me understand.
