### ISSUE TITLE
JoystickGremlin turns off when connecting/disconnecting controller

### ISSUE THREAD

**Issue by Spidey002** [WhiteMagic/JoystickGremlin#420]
Is there a way to keep JoystickGremlin from turning off when connecting or disconnecting a controller?
I use a Hotas and xbox controller in one of my games. But the controller will disconnect when I don't use it for a while. When it does, suddenly, all of my vjoy inputs go dead because JoystickGremlin turns off.

**Comment by WhiteMagic** [comment]
Nothing you can do to change that behavior at this stage, see #276.

**Comment by deliriak666** [comment]
this is still an issue unfortunately - I have to reactivate the profile all the time ))
