### ISSUE TITLE
Conflict with Thrustmaster Target

### ISSUE THREAD

**Issue by aka2k** [WhiteMagic/JoystickGremlin#43]
Going to keep it simple to not take much of your time: every time I try to use TARGET and joystick Gremlin at the same time, I lose the inputs on my TARGET profile. If I try to start the TARGET profile after Gremlin, the Joystick Gremlin crash.

**Comment by WhiteMagic** [comment]
Would you happen to have a sample that causes those issues for you? I've tried getting Gremlin to crash using both TARGET scripts and the TARGET Gui both with essentially empty / default settings and that didn't cause crashes or loss of inputs on the unified TARGET device.

**Comment by aka2k** [comment]
Somehow I couldn't manage to reproduce the crash again, but I'm still losing inputs on Target combined device. I'm attaching the profile I'm using. 

[IL-2 Bos.zip](https://github.com/WhiteMagic/JoystickGremlin/files/753369/IL-2.Bos.zip)

**Comment by aka2k** [comment]
Hi, I'm sorry, but I think the TARGET issues might be on my end only. I'm having issues as well with other tools that use VJoy. I'm gonna investigate that further. Sorry for taking your time and really thank you for the great software. 

I might end up only using Joystick Gremlin after all, since it take almost zero impact on processor time, differently from TARGET and other stuff like JoystickCurves. They do steal quite some CPU cycles.

**Comment by WhiteMagic** [comment]
Closed for now, if more issues come up feel free to reopen or create a new issue item.
