### ISSUE TITLE
Implement switch to previous mode action

### ISSUE THREAD

**Issue by WhiteMagic** [WhiteMagic/JoystickGremlin#437]
Reimplement the switch to previous mode action. There are some options for core behavior changes to be assessed.

Issues that should be looked at when implementing the logic: #417, #296,

**Comment by TheGoodIdeaFairy** [comment]
Small sub-feature request w/ regards to this: a toggle option to allow the "Previous Mode" action on the release of a "Temporary Switch" action to be overridden or cancelled by a subsequent "Mode Switch".  This toggle might be appropriate as a part of the Temp-Switch or the Mode-Switch action.
If this doesn't fit with your planned re-implementation, then by all means disregard.
