### ISSUE TITLE
ACTIVATE toggle and DeActivate when starting xbox 360 controller

### ISSUE THREAD

**Issue by tozstyle** [WhiteMagic/JoystickGremlin#453]
Hi, would like to let you know that while i'm playing star citizen with an xbox 360 controller connected to the pc wirelessly using the official microsoft dongle, the controller might turn off to battery save ( whilst on foot ) once i jump back into the ship and turn on controller Joystick Gremlin de-activates the current profile. I have to switch back to the desktop and activate Joystick gremlin again to get things working. 

Is there any chance of fixing this or/and adding a keybind for an ACTIVATE toggle.

Thanks for your amazing work :)

**Comment by WhiteMagic** [comment]
This is the same issue as #276 and there is no work around, the version recompiled there changes the code to no longer have this behaviour, which future versions will do in a similar way.
