### ISSUE TITLE
BUG: Input Viewer Does Not Scroll Fully With High Device Counts

### ISSUE THREAD

**Issue by TheGoodIdeaFairy** [WhiteMagic/JoystickGremlin#464]
The minimum vertical window size of the input viewer is defined by the number of devices (physical and/or vJoy).  When this number is higher than some limit (determined by screen resolution and scaling) you can no longer view or select devices or button/axis view panels toward the bottom of the window.

**Comment by WhiteMagic** [comment]
Not something that will be fixed in the current version and is not an issue in the new version as the different parts of the UI are in scrollable containers.

**Comment by TheGoodIdeaFairy** [comment]
Awesome, just thought I'd bring it to your attention in case you were planning to recycle that portion of the code.
