### ISSUE TITLE
Condition-Based Shift Button on "Release" does not work

### ISSUE THREAD

**Issue by stormrider123** [WhiteMagic/JoystickGremlin#476]
Following the example "Condition-Based Shift Button", the released state does not generate an action.

https://whitemagic.github.io/JoystickGremlin/examples/

**Comment by WhiteMagic** [comment]
Without additional information on what you actually did it's impossible to help, also typically the discord is easier to get help on these kind of issues. My best bet is that you're using a "Joystick Condition" that should trigger on the input it is has been added to. This won't ever trigger as you're meant to use the "Action Condition" for that specific scenario.
