### ISSUE TITLE
joystick Gremlin and modes

### ISSUE THREAD

**Issue by Stilgar75** [WhiteMagic/JoystickGremlin#477]
Hi, I have set up a profile for DCS using joystick Gremlin, with three modes AA, AG, and navigation. I would like to know if there is a way to avoid having to recreate every command and axis for each mode, essentially making a command unique for each mode.

**Comment by Stilgar75** [comment]
For White Knight, i add that I will never be able to thank you enough for the work you did in Joystick Gremlin. If it weren't for you, I would have had to throw away an entire setup of CH components in the trash!

**Comment by WhiteMagic** [comment]
Duplicating actions is not possible. However, I don't know why you would recreate identical actions for modes. The main point of modes is to remove the need to duplicate unchanged actions and only do those that are different.

Also for this kind of question the discord is a better place as you'd get an answer much quicker there from other users or me.
