### ISSUE TITLE
64 bit version of dill.dll

### ISSUE THREAD

**Issue by muchimi** [WhiteMagic/JoystickGremlin#479]
Hi - looking for info as to where the directinput (dill.dll) came from - looks like it's a 32 bit dll - need the 64 bit version.
Is that available somewhere (package and/or link?)
Thx!

M

**Comment by muchimi** [comment]
Well that took some spelunking  lol: 

Found it here: https://github.com/WhiteMagic/dill

**Comment by WhiteMagic** [comment]
From memory the compiled library you can download there is still 32bit so you will have to compile it from scratch yourself. I can also upload a 64bit version if that's easier for you as I'm using one for the newer version of Gremlin.
