### ISSUE TITLE
LibraryItem error

### ISSUE THREAD

**Issue by muchimi** [WhiteMagic/JoystickGremlin#480]
Hi - I'm looking to compile the current dev branch and getting an error at line 251 in backend.py - 

` library_item = profile_library.LibraryItem()`

LibraryItem is not defined.

Unsure why that is.   Thanks.

**Comment by WhiteMagic** [comment]
Attempting to do anything with the `develop` branch is not going to work as that's just whatever the latest stage of refactor and mangling of internals Gremlin is at at that point in time. There is no attempt made to have this be in any kind of workable state and at the moment isn't and also hasn't been in a while. If you want a working version of the code base that's in the r13 branch or commits tagged with r13.
