### ISSUE TITLE
Plugin configurable variables .value always reporting the initial value not the current value

### ISSUE THREAD

**Issue by WesCov** [WhiteMagic/JoystickGremlin#481]
I have a very simple plugin to play with the ui.  All 3 inputs display, are changeable, and their values are saved in a profile but the .value property in the plugin code only reports the initial values when looking in the logs

![image](https://user-images.githubusercontent.com/121632513/222460521-f1715d85-0d08-4c93-b969-515753356a58.png)

The log shows how the values do not match the controls and are the initial values:
![image](https://user-images.githubusercontent.com/121632513/222605563-ff43b47c-3dc6-4b3c-8655-d8772160dc02.png)

**Comment by WesCov** [comment]
I understand how it works now.  The control values are read at the time the profile is run, and read only at that time.  I was mistakenly thinking the code would reflect the changes as the controls were changed.

**Comment by WhiteMagic** [comment]
The values do change but where you placed the log call does not happen at the time you were thinking. A callback would reflect the actual value.
