### ISSUE TITLE
How to work with Axis Conditions

### ISSUE THREAD

**Issue by Ryuk47** [WhiteMagic/JoystickGremlin#490]
I'm trying to create virtual finger lifts as a means of managing afterburner detents. I cannot for the sake of me get any of the joystick or vjoy conditions to work that say "inside" or "outside" a predefined range, even on a new profile as a condition to send a single button press. Am I doing something wrong or does this not currently work?

**Comment by WhiteMagic** [comment]
This kind of question is better suited for the HOTAS discord (https://discord.gg/szqaJE7) where there is a dedicated channel for Joystick Gremlin talk where many people try to help out with all kinds of usage questions regarding Gremlin.

The description doesn't make it really clear what you're after. However, conditions are unlikely to be necessary as the virtual button functionality should be sufficient together with one or two macros (depending on the type of button press behaviour desired) for entering (and leaving if needed) the range.

**Comment by Ryuk47** [comment]
I will check out that channel, however the issue I am having with the axis in range condition is not specific to what I am trying to achieve. The test case of having a button press or response curve only work while either a joystick or vjoy axis is within a defined range does not work, as in, the button is never pressed or the response curve never applied, which makes me wonder whether the axis conditions are broken.
