### ISSUE TITLE
Reorder containers and actions within the containers

### ISSUE THREAD

**Issue by arenhaus** [WhiteMagic/JoystickGremlin#491]
Once created, containers and actions within the containers stay in the same order. It would be nice to add a way to reorder them by dragging, and to drag actions between containers (e.g. to regroup them under virtual buttons.)

**Comment by WhiteMagic** [comment]
Yeah the dev version already does that, and R14 will have this whenever it ever gets done.

**Comment by arenhaus** [comment]
Good to know, thanks. :)
