### ISSUE TITLE
Axis to Mouse Y axis range?

### ISSUE THREAD

**Issue by hnbdgr1** [WhiteMagic/JoystickGremlin#493]
Hi! i know it's possible to bind an axis slider to Y mouse axis but this only does movement up and down... Is there a way to bind to a particular mouse axis range? I assume maybe this would be done via pixel coordinates? say for 1440p it would be mapped from 0 to 1440? 

Many thanks!

**Comment by WhiteMagic** [comment]
No Gremlin's mouse control is only via relative changes, i.e. what a physical mouse reports to the operating system. The reasons are twofold:
1. Supporting sending absolute positions pushes things dangerously close to automation that will in most instances be considered cheating
2. Most sane games actively ignore absolute mouse positions for the above reason and only work with relative change information

**Comment by hnbdgr1** [comment]
roger that. thanks i'm just trying to create a zoom axis in a game where there is none... it's more of a convenience thing. but i think i've exhausted possibilities as to what can be done. thanks for your answer!
