### ISSUE TITLE
Unable to change Merged axis inversion and senstivity

### ISSUE THREAD

**Issue by Keltskiy** [WhiteMagic/JoystickGremlin#499]
When I merge an Axis I need to invert either the high or low axis on one axis and double the senstivity on the other axis, in order to map a dual throttle to a joystick with a fullrange of motion to the corners of the x and y axis.

I'm trying to achieve the following.

The Average of Throttle X and Y are merged to vJoy Y at %200 sensitvity

The Sum of Throttle X(inverted) and Y are merged to v Joy X at %100 sensitvity

I have an example of this being done in UCR which I will provide but I don't know how to replicate these settings in Joystick Gremlin beyond merging the axis from the actions menu.

Bonus question, Why is the Merge Axis setting part of the Actions Menu and not an an action chosen from the desired virtual device output?

![Screenshot 2023-07-12 131532](https://github.com/WhiteMagic/JoystickGremlin/assets/9003679/2452bcbc-42ea-4398-9345-ffe2b6854932)

![Screenshot 2023-07-12 131603](https://github.com/WhiteMagic/JoystickGremlin/assets/9003679/e3d5a24a-f81e-405b-b01c-59f953fd9705)

**Comment by WhiteMagic** [comment]
Using the built-in dialogue, there is no way to invert an axis before it is being used. If that is needed, a plugin is the only solution. Also, in Gremlin, sensitivity is not something that exists, you adjust a curve to achieve the mapping you desire. For an output of a merge axis, that can be done in the vJoy tab.

**Comment by Keltskiy** [comment]
Thank you
