### ISSUE TITLE
Modes - Wrong one activated

### ISSUE THREAD

**Issue by Rolln-dev** [WhiteMagic/JoystickGremlin#500]
![image](https://github.com/WhiteMagic/JoystickGremlin/assets/8853949/6d935da7-2213-4d2b-afa3-76447fb85797)

As can be seen by the 'Modes' dialog I have 3 modes created.  Base and 2 that inherit from it. As can also been seen I have the 'F-18C Hornet' mode selected but it activates the 'F-15E Eagle' mode.  The 'F-15E Eagle' mode gets activate regardless of what mode I have selected in the top right.

Any ideas?

**Comment by WhiteMagic** [comment]
The selector in the top right has no influence on what mode is active while Gremlin is running. It is purely there to select which mode is being modified.
