### ISSUE TITLE
Joystick Gremlin won't run without vJoy installed and configured

### ISSUE THREAD

**Issue by thalesfm** [WhiteMagic/JoystickGremlin#513]
For some reason the app refuses to open with the error message "vJoy is not present or incorrectly setup" unless it can find at least one vJoy virtual joystick device. I don't know if this is a technical limitation of the app, but it would be nice to be able to use Joystick Gremlin without vJoy if possible since many features of the app don't rely on vJoy at all (like mapping inputs to the mouse & keyboard, for example).

**Comment by WhiteMagic** [comment]
Gremlin was originally designed around vJoy as the only real output option. Other actions were only added over time. As such, there was no point in being able to run the program without vJoy being available and the entire code base assumes that vJoy device(s) exist. R14 might not make the assumption of vJoy at which point launching without it can be implemented. However, in R13 that is entirely impossible.
