### ISSUE TITLE
Incompatible with german standard names for generic controllers

### ISSUE THREAD

**Issue by t0masz407** [WhiteMagic/JoystickGremlin#522]
Hello!

I'm trying to set up a DIY esp32 based bluetooth steering with joystick gremlin and vjoy. 
Unfortunately, due to my windows being set to german, joystick gremlin cant initialize the device name (see picture) since it has the lovely umlaut "ä" in it. 
I can see the problem but i lack any coding knowledge for such programs, so any help would be appreciated.

![grafik](https://github.com/WhiteMagic/JoystickGremlin/assets/23081184/0f4475ae-73bf-49f3-a024-17b4185a6eae)

![grafik](https://github.com/WhiteMagic/JoystickGremlin/assets/23081184/23d05a04-0042-4ff0-87b5-bb029f7b4d5c)
BTW i tried changing the controller name in the windows registry, didnt work.

**Comment by WhiteMagic** [comment]
This is likely related to the same issue as #301 and #369. The fixes there should hopefully work for this instance as well.
