### ISSUE TITLE
Why a little press on a button doesn't write only one letter ?

### ISSUE THREAD

**Issue by samche2000** [WhiteMagic/JoystickGremlin#523]
Hello,

With this configuration mapped on 7 button of VPW Stick WarBRD :
<img width="625" alt="2024-03-24 18_11_19-_tt – Bloc-notes" src="https://github.com/WhiteMagic/JoystickGremlin/assets/14351416/396d7ea9-ff73-4337-936a-861d342a42d2">

When I briefly press the 7 button on the joystick (less than 1 second i mean), there are at least 2 "t" letters which appears. Sometimes more.

How is it possible to translate a press button into an only 1 pulse keyboard button ?

I saw Remap wasn't the solution but it seems that macro is not as easy to configure as it seems.

I tried using a tempo but en exception occurs : Issue #303

My configuration :
- Windows 11 23H2
- Joystick Gremlin 13.3
- VPC WarBRD with VPC Constellation Alpha

Thank you

**Comment by WhiteMagic** [comment]
I quickly replicated your action setup and I get only a single letter being generated, as should be the case. Technically the Count macro setting you have is not necessary, but also doesn't seem to cause an issue on my system. Can you check with the input viewer if you maybe the physical input is repeating by accident or similar?
