### ISSUE TITLE
Succeed to swap to new devices, but now my profiles lost all binding's descriptions

### ISSUE THREAD

**Issue by Psebcool** [WhiteMagic/JoystickGremlin#526]
After 1 year, I'm back to Elite, SC and MFS.

I used gremlin for a long time and I have many profiles with huge amount of custom bindings.

I managed to swap devices via the dedicated option in Gremlin, but after that all actions lost their descriptions. Unable for me to use my profiles in this situation.

But when I open the .xml with a notepad, all the descriptions appears in the files. But not in Gremlin. how can I make them reappear ?

Thanks

**Comment by WhiteMagic** [comment]
That's a known issue with that tool, that it forgets to copy the descriptions over (#447) it also fails with some condition information iirc. The best way to work around at this time is to use a text editor and do a search and replace of the old device GUID with the new one.
