### ISSUE TITLE
JoyStick Gremlin do not read the Profil right

### ISSUE THREAD

**Issue by Lacustat** [WhiteMagic/JoystickGremlin#534]
If i make for example 

Remap: 
Button 1 (from original Joystick)
Vjoy Device 2, Button 1

Condition:
If Vjoy-Device 3, Button 1 is Released

This is how it is in my XML and after Config in Gremlin

When i Restart Gremlin it shows me every Time this:

If Vjoy-Device 3, Button 1 is Pressed

But in the XML it says Released

**Comment by Lacustat** [comment]
Here a Video of the Problem

https://www.youtube.com/watch?v=uHicijbp5qM

**Comment by WhiteMagic** [comment]
This is the same as #361 and happens because the UI does ignore the profile's value and then saves the now wrong state. Some ways to work around it are mentioned in that other issue.
