### ISSUE TITLE
F13-F24 keys don't have labels

### ISSUE THREAD

**Issue by someonemax** [WhiteMagic/JoystickGremlin#536]
F13-F24 keys are not shown with proper labels (F13-F24), but rather with their scan codes, which is quite inconvenient:

<img width="1201" alt="image" src="https://github.com/WhiteMagic/JoystickGremlin/assets/76533230/84370631-359b-45eb-a6cb-3208e50b17be">

**Comment by WhiteMagic** [comment]
See #454
