### ISSUE TITLE
Macro condition state isn't saved

### ISSUE THREAD

**Issue by Ragntard** [WhiteMagic/JoystickGremlin#538]
If I create a simple action with the condition "activate if vJoy 1 Button 1 is released" it automatically changes back to "pressed" instead of released whenever I leave that window.
In the windows game controllers view, everything works as if the "pressed" option is set instead of "released" even if I don't leave the view.

I've tested around with multiple buttons and settings with the same results.

![image](https://github.com/WhiteMagic/JoystickGremlin/assets/80793680/a3f60d16-31ea-4dc5-8d74-c69a0eaed88c)
(This is what I'm trying to set, but it reverts to "Pressed" whenever I leave the window and return.)

Also, if I save everything as an XML file, the file shows the correct state but it still doesn't look right in the GUI or acts as intended when testing the function.

                           <macro>
                                <properties/>
                                <actions>
                                    <vjoy input-id="3" input-type="button" value="True" vjoy-id="1"/>
                                </actions>
                                <activation-condition rule="all">
                                    <condition comparison="released" condition-type="vjoy" id="1" input="button" vjoy-id="1"/>
                                </activation-condition>
                            </macro>
                            
                            
Here I've set up two macros:
![image](https://github.com/WhiteMagic/JoystickGremlin/assets/80793680/be673c48-b752-4a08-ac95-bb7b78e7e481)

When I leave this window and return to it they are both "Pressed"
![image](https://github.com/WhiteMagic/JoystickGremlin/assets/80793680/c735bfa5-6115-4a6c-9e6b-ebb067176339)

I'm on a new install of Joystick Gremlin and it's my first time using it.

**Comment by WhiteMagic** [comment]
This is a known bug (#361) that can be somewhat worked around.

**Comment by Ragntard** [comment]
I also managed to display the right states in UI using the debug version. Then the states display correct (and saves) but the actual macros don't behave as expected. Specifically the release command won't activate even when it displays as such in the UI. But this might be the same issue, I will test some of the workarounds you posted and see if it helps. Thank you so much!

**Comment by WhiteMagic** [comment]
If it's something about the macros themselves unrelated to the UI resetting the condition then feel free to update and reopen this. The whole macro UI will be redone so the bug if there is one might be squashed in that but good to know to look out for it if there is something. There is also some corner cases with Macros triggering with complicated conditions or containers.
