### ISSUE TITLE
Moza R12 wheelbase name issue

### ISSUE THREAD

**Issue by phester66** [WhiteMagic/JoystickGremlin#542]
When I have my Moza R12 wheelbase connected, I get an error regards unable to decode unicode character 0x90.
Traced to DILL\__init__.py class DeviceSummary:, fn init()
Not sure if this is fixed looking at the code, but the current release (13.3) crashes.
For some reason, the OEMName has a 0x90 character at the end, so it's "MOZA R12 Base". I removed the 0x90 from the 2 entries I found in the registry & all is well.
USB Device Viewer entry:
          ===>Interface Descriptor<===
bLength:                           0x09
bDescriptorType:                   0x04
bInterfaceNumber:                  0x02
bAlternateSetting:                 0x00
bNumEndpoints:                     0x02
bInterfaceClass:                   0x03  -> HID Interface Class
bInterfaceSubClass:                0x00
bInterfaceProtocol:                0x00
iInterface:                        0x05
     English (United States)  "MOZA R12 Base"

**Comment by WhiteMagic** [comment]
This boils down to the same error source as #369
