### ISSUE TITLE
Missing file jg_qml.py when building executable

### ISSUE THREAD

**Issue by code-monet** [WhiteMagic/JoystickGremlin#543]
When I try to build the program, it is looking for and failing to find a file that doesn't appear to be in the repository:

```pyinstaller -y --clean joystick_gremlin.spec
152 INFO: PyInstaller: 6.10.0, contrib hooks: 2024.8
153 INFO: Python: 3.10.1
158 INFO: Platform: Windows-10-10.0.19045-SP0
158 INFO: Python environment: <path>\JoystickGremlin\.venv
161 INFO: Removing temporary files and cleaning cache in C:\Users\<user>\AppData\Local\pyinstaller
script '<path>\JoystickGremlin\jg_qml.py' not found
```

Perhaps it's in your local folder and just needs to be included into the Git repo?

**Comment by WhiteMagic** [comment]
Attempting to build the development branch is not intended to work at this stage as it's not ready for release. The spec file that pyinstaller uses simply refers to the old file that is now just `joystick_gremlin.py`, though even changing that, there is no guarantee that it will build and a guarantee that the result won't be a useable version of Gremlin.

**Comment by code-monet** [comment]
Gotcha - is the branch/project in a place where I can contribute pull requests? Even if not, it would be great if you could share some pointers on how you're running the code at the moment (or a subset of the code).

And yes I did change the spec to `joystick_gremlin.py` and like you said, ran into a few issues that I couldn't quickly fix.

**Comment by WhiteMagic** [comment]
The `develop` branch is in a constant state of flux and currently may sometimes be partially broken. I expect that most large-scale changes have been made; however, the only part I'd be confident to say that working on in isolation are actions as they are meant to be quite stand-alone.

The code should run just fine using any IDE you want using the dependencies listed in the `requirements.txt` file using a python version >=3.10 or so. You can see an overview of the things I have planned as parts that need to be done for a R14 release in https://github.com/users/WhiteMagic/projects/1
