### ISSUE TITLE
Decorating joystick problem 

### ISSUE THREAD

**Issue by Francky63** [WhiteMagic/JoystickGremlin#55]
with this simple code taken from doc examples i get - int subscription error -

`import gremlin

tm = gremlin.input_devices.JoystickDecorator(
	"Thrustmaster HOTAS Cougar", 72287232, "Defaul"
)

gremlin.util.log(dir(tm.button)) 

@tm.button(1)
def get_button_1(event):
	if vjoy[1].button(2).is_pressed: 
		vjoy[1].button(2).is_pressed = False  # event.is_pressed
	else:
		vjoy[1].button(2).is_pressed = True   # event.is_pressed
	`

what's wrong??

**Comment by Francky63** [comment]
***SOLVED***
With original code now it works....
`import gremlin
from vjoy.vjoy import AxisName

tm = gremlin.input_devices.JoystickDecorator(
	"Thrustmaster HOTAS Cougar", 72287232, "Default"
)

@tm.button(1)
def get_button_1(event, vjoy):
	if vjoy[1].button(2).is_pressed: 
		vjoy[1].button(2).is_pressed = False  # event.is_pressed
	else:
		vjoy[1].button(2).is_pressed = True   # event.is_pressed
	
	gremlin.util.log("Premuto button 1") 
`

may be something wrong or dirty in memory closed Joystick Greamlin closed vjoy open and reload first version it works

**Comment by WhiteMagic** [comment]
If this happens again, the logfile may contain the actual code piece that caused the error which might allow me to figure out if it's something that Gremlin screwed up. vJoy every now and then is a bit funky and refuses to work correctly on an initial install until reboot / other trial error things.
