### ISSUE TITLE
pulse button

### ISSUE THREAD

**Issue by Francky63** [WhiteMagic/JoystickGremlin#56]
i have to reply what i did in Target and Cougar

I need to set a joy button that if is pressed for less than 3/10 (time is indicative)  of seconds it send normal button on/off
if is pressed for more than 3/10 it start to pulse the button 

this is useful for to set a button as a knob (HSI, HDG compas, ALT ANH setting, volume controll) where one button on is only one step.
as reference i implemented in this way in Cougar
```
REM HSI move fast (pulse) if  button is held for more than DELAY
REM HSI move 1 step if button is depressed for less than DELAY

USE RATE (0)         Rem Nel caso  debba rallentare è possibile aumentare il RATE

DEF X3 DELAY(300) ( T4  OR T5)  AND S3      Rem X3 ON when delay expired button pushed

DEF X1 T4  AND X3            Rem enable X1 burst via HSI_counterClock and S3 after DELAY
DEF X2 T5  AND X3            Rem enable X2 burst via HSI_clock and S3 after DELAY

BTN X1 /A DX22            Rem S3 HSI_counterClock burst shots if X1
BTN X2 /A DX23            Rem S3 HSI_clock burst shots if X2

```
and in this way in Target
```
define HSIup 	PULSE+KEYON+DX4
define HSIdown 	PULSE+KEYON+DX6
	
MapKey(&Throttle, MSR, TEMPO( HSIup, 	REXEC( 1, 50, "ActKey( HSIup);"), 		300));
MapKey(&Throttle, MSL, TEMPO( HSIdown, 	REXEC( 1, 50, "ActKey( HSIdown);"), 	300));

```

**Comment by WhiteMagic** [comment]
Technically you can do this now with Gremlin if you're fine with using a custom module, i.e. python code. I can have a look this evening to see if I can write something similar to this up in form that you can easily adapt for your particular case.

The next version has parts of the building blocks you'd need for your scenario, i.e. long vs. short button press and macros that can repeat at a set rate while a button is held. However, the current implementation wouldn't work as the short / long press is waiting for a release even of a button to trigger and the macro can't yet send joystick button events only keyboard. The macro issue is on my list of things to add after the next release and I'll have a look if there is a decent way to have the short / long to trigger before a release even occurs.

**Comment by WhiteMagic** [comment]
Ok I've got something implemented which will press a button and release it if held for short enough and if held for longer will start pulsing the same button. I hope that's what you were going for, if not let me know or obviously if it doesn't work / gives you problems.

You can find the example here https://github.com/WhiteMagic/JoystickGremlinModules/blob/master/tempo_pulse.py if you want to use it with a Warthog or Cougar you'll have to change the value "72331530" to the appropriate one shown by Gremlin under Tools -> Device Information.

The file I linked above has to be placed in the same folder as the profile you want to use it with and then be added to said profile via the Tools -> Manage Custom Modules dialog where you'll have to enter the name of the module, in this case "tempo_pulse" (without the file extension). Once this is done and the profile is saved you should reload the profile by opening it via File -> Load Profile just to be sure the module will be found correctly.

**Comment by Francky63** [comment]
i'll check thanks

**Comment by Francky63** [comment]
great it works...
but what if I need that also the shift button (button 3 from stick) is pressed?
i tried to use 
t16000.button(3).is_pressed
but is_pressed is not recognized.

**Comment by WhiteMagic** [comment]
I've added an additional example to the same link from above. What it boils down to is that you have to add `joy` as a parameter to the function. That parameter allows you to read values from the physical joysticks in the system. There is a bit of a fiddling required to get the correct ID, they are the system ids starting at 1 and ignoring any vJoy devices.

The reason you can't use the `t16000` object is that this is purely there to create these callbacks that react to user inputs and don't actually know anything about the state of a physical device. I have plans to expose joystick information in a somewhat nicer way. Probably along the lines of having variable names that can be mapped to particular devices via the UI and code. That should allow creating particular configurations that talk about "left stick" and "right stick" but aren't hard coded to say a Warthog and T16000.

**Comment by Francky63** [comment]
Thanks i think this feature can increase set up opportunity great job

**Comment by WhiteMagic** [comment]
R9 provide joystick support for macros and the ability to trigger the short press action on press rather then release. So all these things together should allow this behaviour to be configured directly via the UI rather then having to use a custom module.
See the screenshot for an example of how this should work.
![bandicam 2017-12-09 00-37-30-625](https://user-images.githubusercontent.com/5612/33768196-304f2f1c-dc79-11e7-9eea-0c016a530328.png)

**Comment by Francky63** [comment]
What is it more performing the UI setup or the script?

**Comment by WhiteMagic** [comment]
From a user experience point of view there should be no difference in how both perform, i.e. there should be no lag or anything of the sort.

On a technical level the custom script is slightly more efficient as it doesn't have to jump through some of the generic support structure that exists to allow the usage of various combination of actions, conditions, etc. But even those differences don't account for any real runtime difference that I can measure.
