### ISSUE TITLE
Don't become owner of unmapped yJoy devices and prevent other program from using them

### ISSUE THREAD

**Issue by MarcusWolschon** [WhiteMagic/JoystickGremlin#570]
I have 2 vJoy devices.
The first is the output of Joystick Gremlin.

The second is supposed to be the output of the StreamDeck vJoy plugin.

But JoystickGremlin connects to both vJoy devices as owner (as visible in "vJoyList" with the same PID for both devices.
This prevents the SteamDeck plugin from connecting to the second vJoy device because only one process can be the owner and send virtual joystick inputs.
![grafik](https://github.com/user-attachments/assets/bc03f58a-3195-4834-8324-398e785da41f)

**Comment by WhiteMagic** [comment]
How was this resolved? Was there some stray binding to one of the vJoys? Gremlin is specifically meant to not take ownership of unused devices, so if it did that would be a important to know.
