### ISSUE TITLE
Uncaught exception with Virpil Sticks

### ISSUE THREAD

**Issue by ArcherDuke** [WhiteMagic/JoystickGremlin#575]
I just updated the firmware of my Virpil Sticks and now Joystick Gremlin becomes extremely sluggish as soon as any input is registered and then throws an uncaught exception:
Uncaught exception:
Traceback (most recent call last):
File "joystick_gremlin.py", line 801, in _joystick_input_selection
File "gremlin\ui\input_item.py", line 270, in select_item
File "gremlin\ui\input_item.py", line 155, in event_to_index
KeyError: 6

Doesn't seem to be a problem with the devices names as in other similar issues. Any help at all would be greatly appreciated!

**Comment by ArcherDuke** [comment]
Ok, seems I was stupid and my report premature. There were multiple device entries in the registry for both sticks. I deleted them and now it seems to work. Sorry for bothering you.

**Comment by WhiteMagic** [comment]
No worries.
