### ISSUE TITLE
uncaught exception when 'ALT GR' is pressed

### ISSUE THREAD

**Issue by Francky63** [WhiteMagic/JoystickGremlin#60]
when a profile is active without any keyboard profile i get:
uncaught exception:
Traceback (most recent call last):
File "gremlin\input_devices.py", line 437, in keyboard_event
File "gremlin\macro.py", line 834, in key_from_code
gremlin.error.KeyboardError: 'Invalid scan code specified (541, False)'

Windows 10, Italian keyboard

**Comment by WhiteMagic** [comment]
Ah fun with keys that aren't present on a US keyboard :-) Turns out AltGr sends two key strokes (Alt + Ctrl) which cause fun interactions in the code dealing with keyboard keys. Thanks for reporting this and luckily it was a somewhat easy fix.

Fixed with a3f805f9c813137bbc78ae5d2c8ca19a82dc6e95
