### ISSUE TITLE
Temporary Mode Switch Not Switching Back

### ISSUE THREAD

**Issue by jjensen6823** [WhiteMagic/JoystickGremlin#79]
I have just started using Joystick Gremlin, and I love it, but I've run into one problem.  I am using a throttle with a toggle switch, which I have mapped to "Temporary Mode Switch".  When I toggle the switch on, it switches to the alternate mode, but when I switch it back, nothing happens and I am stuck in alternate mode.  I have left the title of the main mode as default (and named default), and created a second mode called "maneuvering" and made it a daughter mode in mode manager.  I turned on the switch for a windows message when I change modes, and every time I switch the switch on, I get a message, but nothing when I switch back.  The switch reads as "Button 14" on the joystick.  Am I doing something wrong?  I couldn't find any further info in the manual.

Jim 

P.S. I noticed in the log that every time I start Joystick Gremlin I get a bunch of errors about "Requested vJoy device is not available."

![gremlin](https://user-images.githubusercontent.com/35495347/35050317-877477be-fb70-11e7-861d-a721497ce758.jpg)

**Comment by jjensen6823** [comment]
Okay, now I am completely bamboozled.  After rereading the manual as well as the issue about a keyboard key release not doing anything, I decided to handle it as two actions, so I set it up as two "Switch Mode" actions with conditions, one for "pressed" and one for "released".  I did this with both two actions in one container and two separate containers.  In both cases, it switches to "default" when the switch is turned off, but does nothing when it is turned on!  What the heck am I doing wrong?

![gremlin2](https://user-images.githubusercontent.com/35495347/35051863-2eb99bfa-fb74-11e7-8213-cf0a045d7b71.jpg)

![gremlin3](https://user-images.githubusercontent.com/35495347/35051873-33ba89c0-fb74-11e7-97e8-5e2cdb76be4a.jpg)

**Comment by WhiteMagic** [comment]
Technically both ways you attempted should work. The temporary mode switch action performs the same action as the second way you tried but does most of the logic legwork for you.

One reason I can think of why this isn't working is that you have no actions defined in the Maneuvering mode. Gremlin has this annoying behaviour that if a mode is empty, i.e. no actions exist in it, it gets discarded. I have to actually check if I do this on purpose or if it's an odd consequence of how the code is structured.

Another problem can be that if you use the temporary mode switch and start in the Maneuvering mode there is no way for you to switch into the default mode. The temporary mode switch does the following two actions:
- on press: switch to the specified mode
- on release: switch to the previous mode
Thus if there is no previous mode pressing and releasing the button when in the Maneuvering mode will not result in any change.

While it shouldn't make a difference that you use a switch which, as far as Windows is concerned, is just a button you don't have to hold down yourself for it to register as pressed, could you try either option using a normal button. Also make sure you have at least some kind of action assigned in the Maneuvering mode.

There's also the possibility that I have broken the temporary mode action in 9.2 so I'll take a look at that this evening just to make sure it still behaves the way it should.

The logspam about vJoy devices is not an issue. This is essentially Gremlin probing all possible vJoy devices which when it fails results in a log message but is not harmful. Gremlin does this so it can associate the actual vJoy device with the correct windows id.

**Comment by WhiteMagic** [comment]
I've played around quickly with the temporary mode switch action with the setup you have, i.e. Default mode and Maneuvering which inherits from Default. With only the temporary mode switch configured Gremlin switches to Maneuvering on button press and upon release swaps back. So for me at least it behaved as it should even when there is no other action present in Maneuvering.

I think the easiest way to figure out what's wrong is if you could upload your profile xml which would allow me to take a look at it if somehow something in there is off.

**Comment by MedievalBunny** [comment]
I'm having the same problem. 

I just updated to r10 and noticed this. I've been able to reproduce it on a new file as well as a file from r9 which was working just fine before I installed 10. 

I have the button set up with a tempo container, with a short press linked to a vJoy button in one file or a keyboard button in the other and long press activating the temporary mode switch. When the button is held past the long press duration the mode switches and does not switch back on release. In my case a second press of that button will switch the modes back as I have that button mapped to switch mode as a failsafe.

**Comment by WhiteMagic** [comment]
Could you possibly post your profile as I seem incapable of reproducing the issue with a simple setup with a temporary button. Maybe there is something odd that's converted incorrectly between R9 and R10 or there is a odd action present that I'm not adding.

**Comment by MedievalBunny** [comment]
Hmmmm ... this is interesting. Figured I'd take another look at it before posting the file just to be sure, now (of course) it appears to be working. I had tried restarting the computer and reinstalling both Joystick Gremlin and vJoy to no avail the other day. I have since unplugged and re-plugged the controllers so I wonder if that did it. 

I'll keep an eye on this and see if I can reliably reproduce the issue.

**Comment by WhiteMagic** [comment]
Heh yeah that's the usual way of bugs sadly :-) Let me know if this happens again possibly with the profile if it's related to it.

**Comment by neok23** [comment]
Having the same issue, did you ever find out how to fix it?

**Comment by fRENCH321** [comment]
Same, I have been having this issue for while now, so much so that I had to configure a "Switch back to default mode" button to avoid a crash while flying. It is definitely intermittent therefore hard to reproduce. If there is a sure way to automate the switching back to default mode after let's say 3 seconds I will try and set it up
