### ISSUE TITLE
Tempo container error with Falcon BMS

### ISSUE THREAD

**Issue by sanpats** [WhiteMagic/JoystickGremlin#87]
I use one axis lever on my joystick to remap to two buttons in the tempo container.

`<axis description="" id="8">
                    <container activate-on="release" delay="0.5" type="tempo">
                        <action-set>
                            <remap button="8" vjoy="2"/>
                        </action-set>
                        <action-set>
                            <remap button="3" vjoy="2"/>
                        </action-set>
                        <virtual-button direction="anywhere" lower-limit="0.0" upper-limit="1.0"/>
                    </container>
                </axis>`

I test the axis and on windows controller property, it works fine, but when I play Falcon BMS, a F-16 flight sim, I got this error every time I use the axis.

`2018-02-14 20:23:11      ERROR Uncaught exception:
Traceback (most recent call last):
   File "gremlin\event_handler.py", line 496, in process_event
   File "gremlin\execution_graph.py", line 96, in __call__
   File "gremlin\execution_graph.py", line 171, in process_event
   File "container_plugins\tempo\__init__.py", line 257, in process_event
    self.timer.cancel()
 AttributeError: 'NoneType' object has no attribute 'cancel'`

**Comment by sanpats** [comment]
![tempo containner error](https://user-images.githubusercontent.com/22677493/36207408-67d1be58-11c8-11e8-98ab-9bfa7e359b82.png)

**Comment by WhiteMagic** [comment]
That's a rather odd bug, do you know if this happens just with BMS or other games as well? I'll have to look at the code and maybe I can spot something that could cause this type of error.

**Comment by sanpats** [comment]
I’ve note test with other games yet, but with joystick testers it seems to work fine. I’ll check with other games when I have time.

**Comment by sanpats** [comment]
Typo: I’ve not tested......

**Comment by sanpats** [comment]
I found the root cause of the bug. I activate a profile manually before starting the game, while I also tick the "automatically load profile based on current application" option, which also have the game .exe on the list. It somehow activates the profile for the game twice. Either not manually activate the profile or untick the automatically load profile solved the issue.

**Comment by WhiteMagic** [comment]
Oh that kind of makes sense in a weird way. From memory the auto activation stuff forces the activation of the module and might not properly "shutdown" things now that I've changed how I the code that executes a profile is generated. So it is likely to have remnants of old logic and other stuff flying around which results in the actions being triggered that no longer have supporting data etc.

But given you've found a way to reproduce it shouldn't be hard for me to reproduce it with arbitrary programs and then fix it.

**Comment by WhiteMagic** [comment]
Closing for now.
