### ISSUE TITLE
Update Documentation for module location

### ISSUE THREAD

**Issue by owenworley** [WhiteMagic/JoystickGremlin#91]
The current documentation does not explain where to put custom python modules.

I ended up finding a reddit post telling me to put them in the folder containing the .xml profile.

To save others the trouble, please could you update https://whitemagic.github.io/JoystickGremlin/custom_modules/ to include a 'location' section of where to put modules?

**Comment by WhiteMagic** [comment]
Yeah I definitely can do that, also I probably should simply implement a somewhat "smarter" way of adding custom modules. Basically the idea would be to add modules by selecting them with a standard file selection dialog and Gremlin would do the anything else it has to do to make the module work behind the scenes.

**Comment by WhiteMagic** [comment]
Well turned out I didn't ever get around to making that small update but ended up reworking how the custom module bit works. Now it simply requires picking a file and Gremlin will do the rest.

**Comment by owenworley** [comment]
Cool, ill give it a whirl when I get home
