### ISSUE TITLE
Custom Module - periodic function never fires

### ISSUE THREAD

**Issue by owenworley** [WhiteMagic/JoystickGremlin#92]
I am having some real problems trying to get anything in a custom module working.

I have made the simplest script I can think of and I do not see what I would expect in the log viewer. Please can you tell me if I am doing something wrong?

```
import gremlin
from gremlin.input_devices import periodic
gremlin.util.log("Test Script loaded")

@periodic(1)
def periodic_function():
    gremlin.util.log("periodic_function")
```

When I activate the script, the log viewer shows:
2018-03-02 10:37:39 Test Script loaded

It never shows "periodic_function" which I would expect to be shown.

P.S. I am sorry for asking for support through issues, but I do not know how else to reach out

**Comment by owenworley** [comment]
I am using:
Version | Release 10

On windows 10 pro (latest updates), 10.0.16299 Build 16299

I have a saitek x56 throttle and stick attached and T-rudder pedals, and vjoy installed

**Comment by owenworley** [comment]
Never mind, found a work around. Switched to usinging listener functions to achieve what I wanted.

Still seems od that periodic doesnt work.

**Comment by GameOverture** [comment]
I cannot get periodic functions to work either. I could still use it for my needs however. They didn't work back in version 9 either when I tried to use them. 

I've tried different combinations of parameters in periodic_function (vjoy, joy, keyboard), or leaving it empty. Everything else works in my script except the periodic_function never gets invoked.

**Comment by WhiteMagic** [comment]
There's a good chance that I inadvertently broke this with changes I made and since none of my usual configurations uses the feature it's easy to slip through ... one more item to add to my checklist :-)

I'll have a look over the weekend to figure out what's going on with that function.

**Comment by WhiteMagic** [comment]
Ok, finally got some time to work on Gremlin again and looked at this issue. The handling of periodic function stuff was simply broken. I assume this was a knock on effect from redoing and changing the way joystick decorators etc. were handled a while ago. It's now fixed but I'll want to make a few more additions / fixes to Gremlin before releasing a new version.

If you need periodic execution urgently, I probably can write a custom code module that is a cut down version of what is used in Gremlin.

**Comment by GameOverture** [comment]
No rush for me, I can just stub it out for now. Just happy to see it in next version, thanks.
