### ISSUE TITLE
Joystick Curves not working for Elite Dangerous

### ISSUE THREAD

**Issue by ddrake1984** [WhiteMagic/JoystickGremlin#93]
I have followed the youtube instructions and the manual, however the joystick curves do not have any effect in the game Elite Dangerous.

I have tried many permutations of the curve and nothing seems to make a difference.

This was the original configuration I used, however after testing, I found it was not working...
![unknown](https://user-images.githubusercontent.com/6082362/37519525-83748e26-296d-11e8-8183-4313ea258495.png)

these were the configurations I tried to see if joystick curves was working, however I found it had no effect.
![unknown](https://user-images.githubusercontent.com/6082362/37519531-87dbb426-296d-11e8-8bf2-ac1c74cc4574.png)
![unknown](https://user-images.githubusercontent.com/6082362/37519533-8ba540ea-296d-11e8-814f-6548d2806339.png)
![unknown](https://user-images.githubusercontent.com/6082362/37519534-8f02fe80-296d-11e8-96c9-1673bb29c2f1.png)

If there is something I am doing wrong, please let me know, I would gladly upload more content to work this out.

**Comment by WhiteMagic** [comment]
When you made those settings did they work properly in the vJoy device as shown by Windows' joystick control thing (joy.cpl). If it did work there did you bind the vJoy device axes inside ED, as ED won't automatically use those axes.

**Comment by ddrake1984** [comment]
It seems I have fixed the issue, using vjoy monitor I noticed that when I used input repeater, the repeated axis was barely moving (such small increment) and thus wasn't being recognized by the game. I changed the curve to be a bit stronger so when I used input repeater it gave a much larger range of motion for repeated command of the axis and thus fixed the issue of the game not recognizing the repeated axis command.

**Comment by WhiteMagic** [comment]
Good to hear that you worked it out. I can see your second and third curve to cause this issue. The first one, however, should have worked with the repeater.
