### ISSUE TITLE
Gremlin not remembering the same System ID for the Device

### ISSUE THREAD

**Issue by ddrake1984** [WhiteMagic/JoystickGremlin#94]
I'm sure this has been brought up before.

When I start Gremlin, it will load the System ID for each device and assign this into the program.
Joystick 1 (System ID 0)
Joystick 2 (System ID 2)
Pedals (System ID 3)
vjoy (System ID 1)
or something similar... 

when I checked my USB interfaces Joystick 1 is listed as USB1 and Joystick 2 is listed as USB2 (I am using a usb device analyser)

I understand the concept that Gremlin doesn't make the System ID but parses it from the O/S.

What I don't understand is if I unplug and replug the device, it shouldn't change the order, because it should only be parsing the information from the O/S, however it changes the order and this has repeatedly screwed my config settings, this means I have to go into the config and re-adjust the config file each time, sometimes on a reboot, I will find the order for devices has changed. 

this is an easily repeatable issue, if I replug a single device multiple times, the number will keep going up by +1

**Comment by WhiteMagic** [comment]
Is this using identical devices? I'll have to look at what happens with the windows ids when unplugging and replugging a device. While Gremlin uses SDL to get that info I might be doing something silly in the display stage.

However, if you're not using duplicate devices then the windows ID should not matter to Gremlin at all. It will show it and know about it but not use it for deciding about profile mappings. If however, there are multiple identical devices used then the windows id would be used and I'll have to see what windows truly does when unplugging and plugging back in the same device repeatedly.

**Comment by ddrake1984** [comment]
Hey WhiteMagic, I am using identical devices you are correct.. when I get home from work today, I will create a youtube vid if I can demonstrate the issues I am having.

**Comment by WhiteMagic** [comment]
Ok I've looked into this and the underlying issue is that SDL is not reporting the id windows associates with a device but an internal index which increases whenever a new device is connected. So there is no real way around this issue short of seeing how this could be added to SDL and providing a patch or looking at doing all input processing myself without relying on a third part library which relates somewhat to #54.

Meanwhile you should be able to use the device assignment / swapping tool I added in R10 to swap devices around if they get mixed up due to some of this ID issue I think.

**Comment by ddrake1984** [comment]
I will close this issue, the work around I am doing, is going into notepad and changing the ID for the device. I have tried the device swapping tool a while ago and it didn't work for me (I prob did something wrong). At any rate, it seems too difficult to do this SDL and it's not a big enough issue to work on any further as I have a workaround.
