### ISSUE TITLE
remap macro not working

### ISSUE THREAD

**Issue by ddrake1984** [WhiteMagic/JoystickGremlin#95]
I have remapped a button on the joystick to macro the word 'help' as an example.
when I am outside the game, the word help is typed.
when I am inside the game, nothing happens when I press the button.
what am I doing wrong?

**Comment by ddrake1984** [comment]
https://youtu.be/m2kPRpbNip0

**Comment by WhiteMagic** [comment]
Do you happen to launch ED with administrator privileges? I've given this a quick try and for me the macro type the text successfully in ED when both Gremlin and ED were launched with normal user permissions but once I launched ED as admin it didn't work anymore. That behaviour is correct as the way I send keystrokes prevents lower priority processes from sending inputs that could be seen by higher ones.

If you're running both programs as either user or admin then you should see the input in-game. You could try adding delays in between the commands. While Gremlin already adds some small delay on its own this could possibly be not long enough.

**Comment by ddrake1984** [comment]
thanks for this, I was indeed loading up E:D in administrator mode and this is what caused my issues. I have now gotten back into the habit of loading both programs in lower privileges.
