### ISSUE TITLE
Button release not working in V10?

### ISSUE THREAD

**Issue by izolini** [WhiteMagic/JoystickGremlin#96]
Hi, trying to make a single switch function where "press" (switch ON) sends LShift+A and "release" (switch OFF) sends the same key again. Testing using Notepad, JGremlin is only detecting the "press" action, where it sends "A". Releasing the switch does nothing. Tried using several different ways, like using macros, map to keyboard, conditions for container/actions/joystick, single or separated functions, etc. Latest one is shown below: 

![image](https://user-images.githubusercontent.com/8428276/38262305-3e246858-3743-11e8-9347-928979dfc7bf.png)
![image](https://user-images.githubusercontent.com/8428276/38262335-51607d12-3743-11e8-81cb-1d197e96133e.png)

Is this function working on v10? If so, where can I see a simple example?

**Comment by izolini** [comment]
Solved! In short: must use macros to map key presses and select "Action" on conditions.

**Comment by WhiteMagic** [comment]
The UI and explanation on it for what the conditions mean and the overall presentation requires some work as it's extremely barebone and not at all self-explanatory. I'll try to figure out a way to make this easier to figure out by just "looking" at the UI.
